In [1]:
import torch

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print(
        "GPU memory:",
        round(
            torch.cuda.get_device_properties(0).total_memory / 1e9,
            2
        ),
        "GB"
    )

PyTorch: 2.14.1+cu126
CUDA available: True
GPU: Tesla P100-PCIE-16GB
GPU memory: 17.06 GB

In [2]:
import pandas as pd

claims_df = pd.read_csv("fenice_validation_alignscore.csv")

print("Total extracted claims:", len(claims_df))
print(
    "Total articles:",
    claims_df.groupby(["event_id", "article_id"]).ngroups
)
print("Total events:", claims_df["event_id"].nunique())

display(claims_df.head())

Total extracted claims: 1014
Total articles: 30
Total events: 6

,event_id,article_id,passage_id,claim_id,claim,source_passage,alignscore,support_flag
0,6,6.1,6.1_p001,1,Fruit Sold In CA Recalled Due To Hepatitis A O...,Fruit Sold In CA Recalled Due To Hepatitis A O...,0.984695,True
1,6,6.1,6.1_p001,2,Different brands of frozen organic strawberrie...,Fruit Sold In CA Recalled Due To Hepatitis A O...,0.986042,True
2,6,6.1,6.1_p001,3,The FDA recalled two frozen strawberry and tro...,Fruit Sold In CA Recalled Due To Hepatitis A O...,0.996483,True
3,6,6.1,6.1_p001,4,"Scenic Fruit Company of Gresham, Oregon recall...",Fruit Sold In CA Recalled Due To Hepatitis A O...,0.987993,True
4,6,6.1,6.1_p001,5,"Scenic Fruit Company of Gresham, Oregon recall...",Fruit Sold In CA Recalled Due To Hepatitis A O...,0.978279,True

In [3]:
# Selecting the first article in the dataset
article_keys = (
    claims_df[["event_id", "article_id"]]
    .drop_duplicates()
)

event_id, article_id = article_keys.iloc[0]

article_df = claims_df[
    (claims_df["event_id"] == event_id) &
    (claims_df["article_id"] == article_id)
].copy().reset_index(drop=True)

article_claims = article_df["claim"].tolist()

print("Event:", event_id)
print("Article:", article_id)
print("Number of claims:", len(article_claims))

for i, claim in enumerate(article_claims, 1):
    print(f"{i}. {claim}")

Event: 6.0
Article: 6.1
Number of claims: 22
1. Fruit Sold In CA Recalled Due To Hepatitis A Outbreak Frozen organic strawberries and fruit sold throughout California were linked to a possible outbreak of Hepatitis A.
2. Different brands of frozen organic strawberries sold in California were linked to a recent Hepatitis A outbreak.
3. The FDA recalled two frozen strawberry and tropical fruit products sold in California recently.
4. Scenic Fruit Company of Gresham, Oregon recalled Simply Nature frozen organic strawberries sold in Aldi stores.
5. Scenic Fruit Company of Gresham, Oregon recalled an organic tropical fruit blend sold in Trader Joe's grocery stores nationwide due to the outbreak.
6. California Splendor of San Diego recalled bags of their Kirkland Signature Frozen Organic Strawberries.
7. The bags were sold at Costco stores in Los Angeles, two San Diego Business Centers and Hawaii.
8. The company has ceased the production and distribution of the product.
9. The FDA and the company continue their investigation as to what caused the problem.
10. Consumers who have purchased the products are urged to destroy or return it to the place of purchase for a full refund.
11. The frozen organic strawberries were from a common supplier from certain farms in Baja California, Mexico.
12. The frozen organic strawberries were sold to a variety of retailers under multiple brand labels.
13. Epidemological data collected by the Centers for Disease Control.
14. Every person who provided information about what they ate before they get sick reported eating frozen organic strawberries.
15. An identical strain of hepatitis in May 2022 was linked to frozen organic strawberries imported from Baja California.
16. The FDA advised customers who purchased the fruit in the Golden State to check lot codes and best-by dates on the back of each bag.
17. Affected lots and products in California include: Simply Nature Organic Strawberries - Best by June 14, 2024 Trader Joe's Organic Tropical Fruit Blend Pineapple, Bananas, Strawberries & Mango - Best by April 25, 2024/ May 12, 2024/ May 23, 2024/ May 30, 2024/ June 7, 2024 Kirkland Signature Organic Strawberries - Specific lot numbers in L.A., San Diego and Hawaii More Scenic Fruit Company products were recalled nationwide including: Vital Choice Organic Strawberries - Best by Oct. 8, 2024 - Alaska, Idaho, Montana, Oregon, Utah and Washington Made With Organic Strawberries - Best by Nov. 20, 2024 - Illinois, Maryland PCC Community Markets Organic Strawberries - Best by Oct. 29, 2024 - Washington Hepatitis A is a contagious liver disease.
18. Severe cases are rare.
19. The illness can cause liver failure in people who have severe pre-existing illnesses.
20. The illness can cause liver failure in people who are immunocompromised.
21. The FDA said that the illness can cause liver failure in people who have severe pre-existing illnesses.
22. The FDA said that the illness can cause liver failure in people who are immunocompromised.

In [4]:
import torch

print("GPU:", torch.cuda.get_device_name(0))
print("Compute capability:", torch.cuda.get_device_capability(0))
print("GPU memory (GB):",
      round(torch.cuda.get_device_properties(0).total_memory / 1e9, 2))

GPU: Tesla P100-PCIE-16GB
Compute capability: (6, 0)
GPU memory (GB): 17.06

In [5]:
from llama_cpp import Llama
print("llama-cpp-python imported successfully!")

llama-cpp-python imported successfully!

In [6]:
import sys
import subprocess

# Install Hugging Face Hub if needed
subprocess.check_call([
    sys.executable, "-m", "pip",
    "install", "-q", "huggingface_hub"
])

from huggingface_hub import hf_hub_download

model_path = hf_hub_download(
    repo_id="Qwen/Qwen3-8B-GGUF",
    filename="Qwen3-8B-Q4_K_M.gguf",
    local_dir="/project2/xiangren_1987/group_22/models"
)

print("Model downloaded successfully!")
print("Path:", model_path)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Model downloaded successfully!
Path: /project2/xiangren_1987/group_22/models/Qwen3-8B-Q4_K_M.gguf

In [7]:
from llama_cpp import Llama

llm = Llama(
    model_path=model_path,
    n_ctx=4096,
    n_gpu_layers=-1,
    n_threads=4,
    verbose=True
)
print("Qwen3-8B loaded successfully!")

ggml_cuda_init: found 1 CUDA devices (Total VRAM: 16269 MiB):
  Device 0: Tesla P100-PCIE-16GB, compute capability 6.0, VMM: yes, VRAM: 16269 MiB
llama_model_loader: loaded meta data with 28 key-value pairs and 399 tensors from /project2/xiangren_1987/group_22/models/Qwen3-8B-Q4_K_M.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = qwen3
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                               general.name str              = Qwen3 8B Awq Compatible Instruct
llama_model_loader: - kv   3:                           general.finetune str              = awq-compatible-Instruct
llama_model_loader: - kv   4:                           general.basename str              = Qwen3
llama_model_loader: - kv   5:                         general.size_label str              = 8B
llama_model_loader: - kv   6:                          qwen3.block_count u32              = 36
llama_model_loader: - kv   7:                       qwen3.context_length u32              = 40960
llama_model_loader: - kv   8:                     qwen3.embedding_length u32              = 4096
llama_model_loader: - kv   9:                  qwen3.feed_forward_length u32              = 12288
llama_model_loader: - kv  10:                 qwen3.attention.head_count u32              = 32
llama_model_loader: - kv  11:              qwen3.attention.head_count_kv u32              = 8
llama_model_loader: - kv  12:                       qwen3.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  13:     qwen3.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  14:                 qwen3.attention.key_length u32              = 128
llama_model_loader: - kv  15:               qwen3.attention.value_length u32              = 128
llama_model_loader: - kv  16:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  17:                         tokenizer.ggml.pre str              = qwen2
llama_model_loader: - kv  18:                      tokenizer.ggml.tokens arr[str,151936]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  19:                  tokenizer.ggml.token_type arr[i32,151936]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  20:                      tokenizer.ggml.merges arr[str,151387]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv  21:                tokenizer.ggml.eos_token_id u32              = 151645
llama_model_loader: - kv  22:            tokenizer.ggml.padding_token_id u32              = 151643
llama_model_loader: - kv  23:                tokenizer.ggml.bos_token_id u32              = 151643
llama_model_loader: - kv  24:               tokenizer.ggml.add_bos_token bool             = false
llama_model_loader: - kv  25:                    tokenizer.chat_template str              = {%- if tools %}\n    {{- '<|im_start|>...
llama_model_loader: - kv  26:               general.quantization_version u32              = 2
llama_model_loader: - kv  27:                          general.file_type u32              = 15
llama_model_loader: - type  f32:  145 tensors
llama_model_loader: - type q4_K:  217 tensors
llama_model_loader: - type q6_K:   37 tensors
print_info: file format = GGUF V3 (latest)
print_info: file type   = Q4_K - Medium
print_info: file size   = 4.68 GiB (4.90 BPW)
llama_prepare_model_devices: using device CUDA0 (Tesla P100-PCIE-16GB) (0000:81:00.0) - 16011 MiB free
init_tokenizer: initializing tokenizer for type 2
load: 0 unused tokens
load: control token: 151660 '<|fim_middle|>' is not marked as EOG
load: control token: 151659 '<|fim_prefix|>' is not marked as EOG
load: control token: 151653 '<|vision_end|>' is not marked as EOG
load: control token: 151648 '<|box_start|>' is not marked as EOG
load: control token: 151646 '<|object_ref_start|>' is not marked as EOG
load: control token: 151649 '<|box_end|>' is not marked as EOG
load: control-looking token: 128247 '</s>' was not control-type; this is probably a bug in the model. its type will be overridden
load: control token: 151655 '<|image_pad|>' is not marked as EOG
load: control token: 151651 '<|quad_end|>' is not marked as EOG
load: control token: 151647 '<|object_ref_end|>' is not marked as EOG
load: control token: 151652 '<|vision_start|>' is not marked as EOG
load: control token: 151654 '<|vision_pad|>' is not marked as EOG
load: control token: 151656 '<|video_pad|>' is not marked as EOG
load: control token: 151644 '<|im_start|>' is not marked as EOG
load: control token: 151661 '<|fim_suffix|>' is not marked as EOG
load: control token: 151650 '<|quad_start|>' is not marked as EOG
load: printing all EOG tokens:
load:   - 128247 ('</s>')
load:   - 151643 ('<|endoftext|>')
load:   - 151645 ('<|im_end|>')
load:   - 151662 ('<|fim_pad|>')
load:   - 151663 ('<|repo_name|>')
load:   - 151664 ('<|file_sep|>')
load: special tokens cache size = 27
load: token to piece cache size = 0.9311 MB
print_info: arch                  = qwen3
print_info: vocab_only            = 0
print_info: no_alloc              = 0
print_info: n_ctx_train           = 40960
print_info: n_embd_inp            = 4096
print_info: n_embd                = 4096
print_info: n_embd_out            = 4096
print_info: n_layer               = 36
print_info: n_layer_all           = 36
print_info: n_head                = 32
print_info: n_head_kv             = 8
print_info: n_rot                 = 128
print_info: n_swa                 = 0
print_info: is_swa_any            = 0
print_info: non_causal_type       = 0
print_info: n_embd_head_k         = 128
print_info: n_embd_head_v         = 128
print_info: n_gqa                 = 4
print_info: n_embd_k_gqa          = 1024
print_info: n_embd_v_gqa          = 1024
print_info: f_norm_eps            = 0.0e+00
print_info: f_norm_rms_eps        = 1.0e-06
print_info: f_clamp_kqv           = 0.0e+00
print_info: f_max_alibi_bias      = 0.0e+00
print_info: f_logit_scale         = 0.0e+00
print_info: f_attn_scale          = 0.0e+00
print_info: f_attn_value_scale    = 0.0000
print_info: n_ff                  = 12288
print_info: n_expert              = 0
print_info: n_expert_used         = 0
print_info: n_expert_groups       = 0
print_info: n_group_used          = 0
print_info: causal attn           = 1
print_info: pooling type          = -1
print_info: rope type             = 2
print_info: rope scaling          = linear
print_info: freq_base_train       = 1000000.0
print_info: freq_scale_train      = 1
print_info: n_ctx_orig_yarn       = 40960
print_info: rope_yarn_log_mul     = 0.0000
print_info: rope_finetuned        = unknown
print_info: model type            = 8B
print_info: model params          = 8.19 B
print_info: general.name          = Qwen3 8B Awq Compatible Instruct
print_info: vocab type            = BPE
print_info: n_vocab               = 151936
print_info: n_merges              = 151387
print_info: BOS token             = 151643 '<|endoftext|>'
print_info: EOS token             = 151645 '<|im_end|>'
print_info: EOT token             = 151645 '<|im_end|>'
print_info: PAD token             = 151643 '<|endoftext|>'
print_info: LF token              = 198 'Ċ'
print_info: FIM PRE token         = 151659 '<|fim_prefix|>'
print_info: FIM SUF token         = 151661 '<|fim_suffix|>'
print_info: FIM MID token         = 151660 '<|fim_middle|>'
print_info: FIM PAD token         = 151662 '<|fim_pad|>'
print_info: FIM REP token         = 151663 '<|repo_name|>'
print_info: FIM SEP token         = 151664 '<|file_sep|>'
print_info: EOG token             = 128247 '</s>'
print_info: EOG token             = 151643 '<|endoftext|>'
print_info: EOG token             = 151645 '<|im_end|>'
print_info: EOG token             = 151662 '<|fim_pad|>'
print_info: EOG token             = 151663 '<|repo_name|>'
print_info: EOG token             = 151664 '<|file_sep|>'
print_info: max token length      = 256
load_tensors: loading model tensors, this can take a while... (load_mode = mmap)
load_tensors: layer   0 assigned to device CUDA0, is_swa = 0
load_tensors: layer   1 assigned to device CUDA0, is_swa = 0
load_tensors: layer   2 assigned to device CUDA0, is_swa = 0
load_tensors: layer   3 assigned to device CUDA0, is_swa = 0
load_tensors: layer   4 assigned to device CUDA0, is_swa = 0
load_tensors: layer   5 assigned to device CUDA0, is_swa = 0
load_tensors: layer   6 assigned to device CUDA0, is_swa = 0
load_tensors: layer   7 assigned to device CUDA0, is_swa = 0
load_tensors: layer   8 assigned to device CUDA0, is_swa = 0
load_tensors: layer   9 assigned to device CUDA0, is_swa = 0
load_tensors: layer  10 assigned to device CUDA0, is_swa = 0
load_tensors: layer  11 assigned to device CUDA0, is_swa = 0
load_tensors: layer  12 assigned to device CUDA0, is_swa = 0
load_tensors: layer  13 assigned to device CUDA0, is_swa = 0
load_tensors: layer  14 assigned to device CUDA0, is_swa = 0
load_tensors: layer  15 assigned to device CUDA0, is_swa = 0
load_tensors: layer  16 assigned to device CUDA0, is_swa = 0
load_tensors: layer  17 assigned to device CUDA0, is_swa = 0
load_tensors: layer  18 assigned to device CUDA0, is_swa = 0
load_tensors: layer  19 assigned to device CUDA0, is_swa = 0
load_tensors: layer  20 assigned to device CUDA0, is_swa = 0
load_tensors: layer  21 assigned to device CUDA0, is_swa = 0
load_tensors: layer  22 assigned to device CUDA0, is_swa = 0
load_tensors: layer  23 assigned to device CUDA0, is_swa = 0
load_tensors: layer  24 assigned to device CUDA0, is_swa = 0
load_tensors: layer  25 assigned to device CUDA0, is_swa = 0
load_tensors: layer  26 assigned to device CUDA0, is_swa = 0
load_tensors: layer  27 assigned to device CUDA0, is_swa = 0
load_tensors: layer  28 assigned to device CUDA0, is_swa = 0
load_tensors: layer  29 assigned to device CUDA0, is_swa = 0
load_tensors: layer  30 assigned to device CUDA0, is_swa = 0
load_tensors: layer  31 assigned to device CUDA0, is_swa = 0
load_tensors: layer  32 assigned to device CUDA0, is_swa = 0
load_tensors: layer  33 assigned to device CUDA0, is_swa = 0
load_tensors: layer  34 assigned to device CUDA0, is_swa = 0
load_tensors: layer  35 assigned to device CUDA0, is_swa = 0
load_tensors: layer  36 assigned to device CUDA0, is_swa = 0
create_tensor: loading tensor token_embd.weight
create_tensor: loading tensor output_norm.weight
create_tensor: loading tensor output.weight
create_tensor: loading tensor cls.output.weight
create_tensor: loading tensor blk.0.attn_norm.weight
create_tensor: loading tensor blk.0.attn_qkv.weight
create_tensor: loading tensor blk.0.attn_q.weight
create_tensor: loading tensor blk.0.attn_k.weight
create_tensor: loading tensor blk.0.attn_v.weight
create_tensor: loading tensor blk.0.attn_q.bias
create_tensor: loading tensor blk.0.attn_k.bias
create_tensor: loading tensor blk.0.attn_v.bias
create_tensor: loading tensor blk.0.attn_output.weight
create_tensor: loading tensor blk.0.attn_k_norm.weight
create_tensor: loading tensor blk.0.attn_q_norm.weight
create_tensor: loading tensor blk.0.ffn_norm.weight
create_tensor: loading tensor blk.0.ffn_gate.weight
create_tensor: loading tensor blk.0.ffn_down.weight
create_tensor: loading tensor blk.0.ffn_up.weight
create_tensor: loading tensor blk.1.attn_norm.weight
create_tensor: loading tensor blk.1.attn_qkv.weight
create_tensor: loading tensor blk.1.attn_q.weight
create_tensor: loading tensor blk.1.attn_k.weight
create_tensor: loading tensor blk.1.attn_v.weight
create_tensor: loading tensor blk.1.attn_q.bias
create_tensor: loading tensor blk.1.attn_k.bias
create_tensor: loading tensor blk.1.attn_v.bias
create_tensor: loading tensor blk.1.attn_output.weight
create_tensor: loading tensor blk.1.attn_k_norm.weight
create_tensor: loading tensor blk.1.attn_q_norm.weight
create_tensor: loading tensor blk.1.ffn_norm.weight
create_tensor: loading tensor blk.1.ffn_gate.weight
create_tensor: loading tensor blk.1.ffn_down.weight
create_tensor: loading tensor blk.1.ffn_up.weight
create_tensor: loading tensor blk.2.attn_norm.weight
create_tensor: loading tensor blk.2.attn_qkv.weight
create_tensor: loading tensor blk.2.attn_q.weight
create_tensor: loading tensor blk.2.attn_k.weight
create_tensor: loading tensor blk.2.attn_v.weight
create_tensor: loading tensor blk.2.attn_q.bias
create_tensor: loading tensor blk.2.attn_k.bias
create_tensor: loading tensor blk.2.attn_v.bias
create_tensor: loading tensor blk.2.attn_output.weight
create_tensor: loading tensor blk.2.attn_k_norm.weight
create_tensor: loading tensor blk.2.attn_q_norm.weight
create_tensor: loading tensor blk.2.ffn_norm.weight
create_tensor: loading tensor blk.2.ffn_gate.weight
create_tensor: loading tensor blk.2.ffn_down.weight
create_tensor: loading tensor blk.2.ffn_up.weight
create_tensor: loading tensor blk.3.attn_norm.weight
create_tensor: loading tensor blk.3.attn_qkv.weight
create_tensor: loading tensor blk.3.attn_q.weight
create_tensor: loading tensor blk.3.attn_k.weight
create_tensor: loading tensor blk.3.attn_v.weight
create_tensor: loading tensor blk.3.attn_q.bias
create_tensor: loading tensor blk.3.attn_k.bias
create_tensor: loading tensor blk.3.attn_v.bias
create_tensor: loading tensor blk.3.attn_output.weight
create_tensor: loading tensor blk.3.attn_k_norm.weight
create_tensor: loading tensor blk.3.attn_q_norm.weight
create_tensor: loading tensor blk.3.ffn_norm.weight
create_tensor: loading tensor blk.3.ffn_gate.weight
create_tensor: loading tensor blk.3.ffn_down.weight
create_tensor: loading tensor blk.3.ffn_up.weight
create_tensor: loading tensor blk.4.attn_norm.weight
create_tensor: loading tensor blk.4.attn_qkv.weight
create_tensor: loading tensor blk.4.attn_q.weight
create_tensor: loading tensor blk.4.attn_k.weight
create_tensor: loading tensor blk.4.attn_v.weight
create_tensor: loading tensor blk.4.attn_q.bias
create_tensor: loading tensor blk.4.attn_k.bias
create_tensor: loading tensor blk.4.attn_v.bias
create_tensor: loading tensor blk.4.attn_output.weight
create_tensor: loading tensor blk.4.attn_k_norm.weight
create_tensor: loading tensor blk.4.attn_q_norm.weight
create_tensor: loading tensor blk.4.ffn_norm.weight
create_tensor: loading tensor blk.4.ffn_gate.weight
create_tensor: loading tensor blk.4.ffn_down.weight
create_tensor: loading tensor blk.4.ffn_up.weight
create_tensor: loading tensor blk.5.attn_norm.weight
create_tensor: loading tensor blk.5.attn_qkv.weight
create_tensor: loading tensor blk.5.attn_q.weight
create_tensor: loading tensor blk.5.attn_k.weight
create_tensor: loading tensor blk.5.attn_v.weight
create_tensor: loading tensor blk.5.attn_q.bias
create_tensor: loading tensor blk.5.attn_k.bias
create_tensor: loading tensor blk.5.attn_v.bias
create_tensor: loading tensor blk.5.attn_output.weight
create_tensor: loading tensor blk.5.attn_k_norm.weight
create_tensor: loading tensor blk.5.attn_q_norm.weight
create_tensor: loading tensor blk.5.ffn_norm.weight
create_tensor: loading tensor blk.5.ffn_gate.weight
create_tensor: loading tensor blk.5.ffn_down.weight
create_tensor: loading tensor blk.5.ffn_up.weight
create_tensor: loading tensor blk.6.attn_norm.weight
create_tensor: loading tensor blk.6.attn_qkv.weight
create_tensor: loading tensor blk.6.attn_q.weight
create_tensor: loading tensor blk.6.attn_k.weight
create_tensor: loading tensor blk.6.attn_v.weight
create_tensor: loading tensor blk.6.attn_q.bias
create_tensor: loading tensor blk.6.attn_k.bias
create_tensor: loading tensor blk.6.attn_v.bias
create_tensor: loading tensor blk.6.attn_output.weight
create_tensor: loading tensor blk.6.attn_k_norm.weight
create_tensor: loading tensor blk.6.attn_q_norm.weight
create_tensor: loading tensor blk.6.ffn_norm.weight
create_tensor: loading tensor blk.6.ffn_gate.weight
create_tensor: loading tensor blk.6.ffn_down.weight
create_tensor: loading tensor blk.6.ffn_up.weight
create_tensor: loading tensor blk.7.attn_norm.weight
create_tensor: loading tensor blk.7.attn_qkv.weight
create_tensor: loading tensor blk.7.attn_q.weight
create_tensor: loading tensor blk.7.attn_k.weight
create_tensor: loading tensor blk.7.attn_v.weight
create_tensor: loading tensor blk.7.attn_q.bias
create_tensor: loading tensor blk.7.attn_k.bias
create_tensor: loading tensor blk.7.attn_v.bias
create_tensor: loading tensor blk.7.attn_output.weight
create_tensor: loading tensor blk.7.attn_k_norm.weight
create_tensor: loading tensor blk.7.attn_q_norm.weight
create_tensor: loading tensor blk.7.ffn_norm.weight
create_tensor: loading tensor blk.7.ffn_gate.weight
create_tensor: loading tensor blk.7.ffn_down.weight
create_tensor: loading tensor blk.7.ffn_up.weight
create_tensor: loading tensor blk.8.attn_norm.weight
create_tensor: loading tensor blk.8.attn_qkv.weight
create_tensor: loading tensor blk.8.attn_q.weight
create_tensor: loading tensor blk.8.attn_k.weight
create_tensor: loading tensor blk.8.attn_v.weight
create_tensor: loading tensor blk.8.attn_q.bias
create_tensor: loading tensor blk.8.attn_k.bias
create_tensor: loading tensor blk.8.attn_v.bias
create_tensor: loading tensor blk.8.attn_output.weight
create_tensor: loading tensor blk.8.attn_k_norm.weight
create_tensor: loading tensor blk.8.attn_q_norm.weight
create_tensor: loading tensor blk.8.ffn_norm.weight
create_tensor: loading tensor blk.8.ffn_gate.weight
create_tensor: loading tensor blk.8.ffn_down.weight
create_tensor: loading tensor blk.8.ffn_up.weight
create_tensor: loading tensor blk.9.attn_norm.weight
create_tensor: loading tensor blk.9.attn_qkv.weight
create_tensor: loading tensor blk.9.attn_q.weight
create_tensor: loading tensor blk.9.attn_k.weight
create_tensor: loading tensor blk.9.attn_v.weight
create_tensor: loading tensor blk.9.attn_q.bias
create_tensor: loading tensor blk.9.attn_k.bias
create_tensor: loading tensor blk.9.attn_v.bias
create_tensor: loading tensor blk.9.attn_output.weight
create_tensor: loading tensor blk.9.attn_k_norm.weight
create_tensor: loading tensor blk.9.attn_q_norm.weight
create_tensor: loading tensor blk.9.ffn_norm.weight
create_tensor: loading tensor blk.9.ffn_gate.weight
create_tensor: loading tensor blk.9.ffn_down.weight
create_tensor: loading tensor blk.9.ffn_up.weight
create_tensor: loading tensor blk.10.attn_norm.weight
create_tensor: loading tensor blk.10.attn_qkv.weight
create_tensor: loading tensor blk.10.attn_q.weight
create_tensor: loading tensor blk.10.attn_k.weight
create_tensor: loading tensor blk.10.attn_v.weight
create_tensor: loading tensor blk.10.attn_q.bias
create_tensor: loading tensor blk.10.attn_k.bias
create_tensor: loading tensor blk.10.attn_v.bias
create_tensor: loading tensor blk.10.attn_output.weight
create_tensor: loading tensor blk.10.attn_k_norm.weight
create_tensor: loading tensor blk.10.attn_q_norm.weight
create_tensor: loading tensor blk.10.ffn_norm.weight
create_tensor: loading tensor blk.10.ffn_gate.weight
create_tensor: loading tensor blk.10.ffn_down.weight
create_tensor: loading tensor blk.10.ffn_up.weight
create_tensor: loading tensor blk.11.attn_norm.weight
create_tensor: loading tensor blk.11.attn_qkv.weight
create_tensor: loading tensor blk.11.attn_q.weight
create_tensor: loading tensor blk.11.attn_k.weight
create_tensor: loading tensor blk.11.attn_v.weight
create_tensor: loading tensor blk.11.attn_q.bias
create_tensor: loading tensor blk.11.attn_k.bias
create_tensor: loading tensor blk.11.attn_v.bias
create_tensor: loading tensor blk.11.attn_output.weight
create_tensor: loading tensor blk.11.attn_k_norm.weight
create_tensor: loading tensor blk.11.attn_q_norm.weight
create_tensor: loading tensor blk.11.ffn_norm.weight
create_tensor: loading tensor blk.11.ffn_gate.weight
create_tensor: loading tensor blk.11.ffn_down.weight
create_tensor: loading tensor blk.11.ffn_up.weight
create_tensor: loading tensor blk.12.attn_norm.weight

Qwen3-8B loaded successfully!

Using gguf chat template: {%- if tools %}
    {{- '<|im_start|>system\n' }}
    {%- if messages[0].role == 'system' %}
        {{- messages[0].content + '\n\n' }}
    {%- endif %}
    {{- "# Tools\n\nYou may call one or more functions to assist with the user query.\n\nYou are provided with function signatures within <tools></tools> XML tags:\n<tools>" }}
    {%- for tool in tools %}
        {{- "\n" }}
        {{- tool | tojson }}
    {%- endfor %}
    {{- "\n</tools>\n\nFor each function call, return a json object with function name and arguments within <tool_call></tool_call> XML tags:\n<tool_call>\n{\"name\": <function-name>, \"arguments\": <args-json-object>}\n</tool_call><|im_end|>\n" }}
{%- else %}
    {%- if messages[0].role == 'system' %}
        {{- '<|im_start|>system\n' + messages[0].content + '<|im_end|>\n' }}
    {%- endif %}
{%- endif %}
{%- set ns = namespace(multi_step_tool=true, last_query_index=messages|length - 1) %}
{%- for index in range(ns.last_query_index, -1, -1) %}
    {%- set message = messages[index] %}
    {%- if ns.multi_step_tool and message.role == "user" and not('<tool_response>' in message.content and '</tool_response>' in message.content) %}
        {%- set ns.multi_step_tool = false %}
        {%- set ns.last_query_index = index %}
    {%- endif %}
{%- endfor %}
{%- for message in messages %}
    {%- if (message.role == "user") or (message.role == "system" and not loop.first) %}
        {{- '<|im_start|>' + message.role + '\n' + message.content + '<|im_end|>' + '\n' }}
    {%- elif message.role == "assistant" %}
        {%- set content = message.content %}
        {%- set reasoning_content = '' %}
        {%- if message.reasoning_content is defined and message.reasoning_content is not none %}
            {%- set reasoning_content = message.reasoning_content %}
        {%- else %}
            {%- if '</think>' in message.content %}
                {%- set content = message.content.split('</think>')[-1].lstrip('\n') %}
                {%- set reasoning_content = message.content.split('</think>')[0].rstrip('\n').split('<think>')[-1].lstrip('\n') %}
            {%- endif %}
        {%- endif %}
        {%- if loop.index0 > ns.last_query_index %}
            {%- if loop.last or (not loop.last and reasoning_content) %}
                {{- '<|im_start|>' + message.role + '\n<think>\n' + reasoning_content.strip('\n') + '\n</think>\n\n' + content.lstrip('\n') }}
            {%- else %}
                {{- '<|im_start|>' + message.role + '\n' + content }}
            {%- endif %}
        {%- else %}
            {{- '<|im_start|>' + message.role + '\n' + content }}
        {%- endif %}
        {%- if message.tool_calls %}
            {%- for tool_call in message.tool_calls %}
                {%- if (loop.first and content) or (not loop.first) %}
                    {{- '\n' }}
                {%- endif %}
                {%- if tool_call.function %}
                    {%- set tool_call = tool_call.function %}
                {%- endif %}
                {{- '<tool_call>\n{"name": "' }}
                {{- tool_call.name }}
                {{- '", "arguments": ' }}
                {%- if tool_call.arguments is string %}
                    {{- tool_call.arguments }}
                {%- else %}
                    {{- tool_call.arguments | tojson }}
                {%- endif %}
                {{- '}\n</tool_call>' }}
            {%- endfor %}
        {%- endif %}
        {{- '<|im_end|>\n' }}
    {%- elif message.role == "tool" %}
        {%- if loop.first or (messages[loop.index0 - 1].role != "tool") %}
            {{- '<|im_start|>user' }}
        {%- endif %}
        {{- '\n<tool_response>\n' }}
        {{- message.content }}
        {{- '\n</tool_response>' }}
        {%- if loop.last or (messages[loop.index0 + 1].role != "tool") %}
            {{- '<|im_end|>\n' }}
        {%- endif %}
    {%- endif %}
{%- endfor %}
{%- if add_generation_prompt %}
    {{- '<|im_start|>assistant\n' }}
    {%- if enable_thinking is defined and enable_thinking is false %}
        {{- '<think>\n\n</think>\n\n' }}
    {%- endif %}
{%- endif %}
Using chat eos_token: <|im_end|>
Using chat bos_token: <|endoftext|>

In [8]:
REDUNDANCY_PROMPT = """
You are evaluating semantic redundancy in factual claims
extracted from news articles.

Your task is to identify claims that repeat substantially
the same factual information.

Two claims are redundant if:
- They express the same core factual assertion.
- Differences in wording do not change their meaning.
- Keeping both provides little or no additional
  factual information.

Two claims are NOT redundant if:
- They describe different events or actions.
- They differ meaningfully in entities, numbers,
  dates, negation, or uncertainty.
- One provides substantial additional factual
  information absent from the other.
- They merely discuss the same general topic.

Instructions:
- Evaluate meaning, not word overlap.
- Do not assume duplicates exist.
- Do not rewrite claims.
- Each claim ID can appear in at most one group.
- Return only groups with at least two claims.

Return valid JSON:
{"duplicate_groups": []}
"""

In [9]:
import json

numbered_claims = "\n".join(
    f"{i}. {claim}"
    for i, claim in enumerate(article_claims, 1)
)
response = llm.create_chat_completion(
    messages=[
        {
            "role": "system",
            "content": REDUNDANCY_PROMPT
        },
        {
            "role": "user",
            "content": (
                "/no_think\n"
                "CLAIMS TO EVALUATE:\n"
                + numbered_claims
            )
        }
    ],
    temperature=0,
    max_tokens=300,
    response_format={
        "type": "json_object"
    }
)

generated = response["choices"][0]["message"]["content"]

print("RAW RESPONSE:")
print(generated)

result = json.loads(generated)
duplicate_groups = result["duplicate_groups"]
print("\nDuplicate groups:", duplicate_groups)

ggml_cuda_graph_set_enabled: disabling CUDA graphs due to GPU architecture
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =    1550.85 ms /   870 tokens (    1.78 ms per token,   560.98 tokens per second)
llama_perf_context_print:        eval time =    3016.22 ms /    98 runs   (   30.78 ms per token,    32.49 tokens per second)
llama_perf_context_print:       total time =    8266.39 ms /   968 tokens
llama_perf_context_print:    graphs reused =         97

RAW RESPONSE:
{"duplicate_groups": [{"group": ["1", "2"]}, {"group": ["3", "17"]}, {"group": ["4", "6", "17"]}, {"group": ["5", "17"]}, {"group": ["11", "15"]}, {"group": ["14", "17"]}, {"group": ["16", "17"]}, {"group": ["21", "22"]}]}


Duplicate groups: [{'group': ['1', '2']}, {'group': ['3', '17']}, {'group': ['4', '6', '17']}, {'group': ['5', '17']}, {'group': ['11', '15']}, {'group': ['14', '17']}, {'group': ['16', '17']}, {'group': ['21', '22']}]

In [10]:
import pandas as pd

redundant_copies = sum(
    len(group) - 1
    for group in duplicate_groups
)

redundancy_rate = (
    redundant_copies / len(article_claims)
)

print("Total claims:", len(article_claims))
print("Duplicate groups:", duplicate_groups)
print("Redundant copies:", redundant_copies)
print(f"Redundancy rate: {redundancy_rate:.2%}")

results_df = pd.DataFrame({
    "event_id": [event_id],
    "article_id": [article_id],
    "total_claims": [len(article_claims)],
    "duplicate_groups": [json.dumps(duplicate_groups)],
    "redundant_copies": [redundant_copies],
    "redundancy_rate": [redundancy_rate]
})

results_df.to_csv(
    "qwen_redundancy_one_article.csv",
    index=False
)

print("Results saved!")

Total claims: 22
Duplicate groups: [{'group': ['1', '2']}, {'group': ['3', '17']}, {'group': ['4', '6', '17']}, {'group': ['5', '17']}, {'group': ['11', '15']}, {'group': ['14', '17']}, {'group': ['16', '17']}, {'group': ['21', '22']}]
Redundant copies: 0
Redundancy rate: 0.00%
Results saved!

In [11]:
import huggingface_hub
import transformers

print("Hugging Face Hub:", huggingface_hub.__version__)
print("Transformers:", transformers.__version__)

from sentence_transformers import SentenceTransformer

print("Sentence Transformers imported successfully!")

Hugging Face Hub: 1.33.0
Transformers: 5.20.1
Sentence Transformers imported successfully!

In [13]:
from sentence_transformers import SentenceTransformer
import torch

sbert = SentenceTransformer(
    "sentence-transformers/all-mpnet-base-v2",
    device="cpu"
)

print("SBERT loaded successfully!")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/11.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  438MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

SBERT loaded successfully!

In [14]:
import numpy as np
import pandas as pd
from sentence_transformers import util

# article_claims contains the 22 FENICE claims
embeddings = sbert.encode(
    article_claims,
    convert_to_tensor=True,
    normalize_embeddings=True
)

similarity_matrix = util.cos_sim(
    embeddings,
    embeddings
).cpu().numpy()

pairs = []

for i in range(len(article_claims)):
    for j in range(i + 1, len(article_claims)):

        pairs.append({
            "Claim 1 ID": i + 1,
            "Claim 2 ID": j + 1,
            "Similarity": float(similarity_matrix[i, j]),
            "Claim 1": article_claims[i],
            "Claim 2": article_claims[j]
        })

pairs_df = pd.DataFrame(pairs)
pairs_df = pairs_df.sort_values(
    "Similarity",
    ascending=False
).reset_index(drop=True)

print("Total possible pairs:", len(pairs_df))
display(
    pairs_df.head(20)
)

Total possible pairs: 231

,Claim 1 ID,Claim 2 ID,Similarity,Claim 1,Claim 2
0,19,21,0.961154,The illness can cause liver failure in people ...,The FDA said that the illness can cause liver ...
1,20,22,0.959762,The illness can cause liver failure in people ...,The FDA said that the illness can cause liver ...
2,1,2,0.883355,Fruit Sold In CA Recalled Due To Hepatitis A O...,Different brands of frozen organic strawberrie...
3,2,15,0.868105,Different brands of frozen organic strawberrie...,An identical strain of hepatitis in May 2022 w...
4,1,17,0.859105,Fruit Sold In CA Recalled Due To Hepatitis A O...,Affected lots and products in California inclu...
5,21,22,0.854232,The FDA said that the illness can cause liver ...,The FDA said that the illness can cause liver ...
6,19,20,0.831124,The illness can cause liver failure in people ...,The illness can cause liver failure in people ...
7,19,22,0.820556,The illness can cause liver failure in people ...,The FDA said that the illness can cause liver ...
8,1,3,0.808464,Fruit Sold In CA Recalled Due To Hepatitis A O...,The FDA recalled two frozen strawberry and tro...
9,20,21,0.794553,The illness can cause liver failure in people ...,The FDA said that the illness can cause liver ...
10,2,17,0.790072,Different brands of frozen organic strawberrie...,Affected lots and products in California inclu...
11,3,6,0.781593,The FDA recalled two frozen strawberry and tro...,California Splendor of San Diego recalled bags...
12,11,12,0.778286,The frozen organic strawberries were from a co...,The frozen organic strawberries were sold to a...
13,4,6,0.771233,"Scenic Fruit Company of Gresham, Oregon recall...",California Splendor of San Diego recalled bags...
14,1,15,0.761735,Fruit Sold In CA Recalled Due To Hepatitis A O...,An identical strain of hepatitis in May 2022 w...
15,4,17,0.748337,"Scenic Fruit Company of Gresham, Oregon recall...",Affected lots and products in California inclu...
16,3,4,0.747503,The FDA recalled two frozen strawberry and tro...,"Scenic Fruit Company of Gresham, Oregon recall..."
17,4,5,0.747274,"Scenic Fruit Company of Gresham, Oregon recall...","Scenic Fruit Company of Gresham, Oregon recall..."
18,6,17,0.747105,California Splendor of San Diego recalled bags...,Affected lots and products in California inclu...
19,3,17,0.745597,The FDA recalled two frozen strawberry and tro...,Affected lots and products in California inclu...

In [15]:
for _, row in pairs_df.head(15).iterrows():

    print("=" * 65)
    print(
        f"Claims {int(row['Claim 1 ID'])} "
        f"& {int(row['Claim 2 ID'])}"
    )
    print(f"Similarity: {row['Similarity']:.4f}")

    print("\nClaim A:")
    print(row["Claim 1"])

    print("\nClaim B:")
    print(row["Claim 2"])
    print()

=================================================================
Claims 19 & 21
Similarity: 0.9612

Claim A:
The illness can cause liver failure in people who have severe pre-existing illnesses.

Claim B:
The FDA said that the illness can cause liver failure in people who have severe pre-existing illnesses.

=================================================================
Claims 20 & 22
Similarity: 0.9598

Claim A:
The illness can cause liver failure in people who are immunocompromised.

Claim B:
The FDA said that the illness can cause liver failure in people who are immunocompromised.

=================================================================
Claims 1 & 2
Similarity: 0.8834

Claim A:
Fruit Sold In CA Recalled Due To Hepatitis A Outbreak Frozen organic strawberries and fruit sold throughout California were linked to a possible outbreak of Hepatitis A.

Claim B:
Different brands of frozen organic strawberries sold in California were linked to a recent Hepatitis A outbreak.

=================================================================
Claims 2 & 15
Similarity: 0.8681

Claim A:
Different brands of frozen organic strawberries sold in California were linked to a recent Hepatitis A outbreak.

Claim B:
An identical strain of hepatitis in May 2022 was linked to frozen organic strawberries imported from Baja California.

=================================================================
Claims 1 & 17
Similarity: 0.8591

Claim A:
Fruit Sold In CA Recalled Due To Hepatitis A Outbreak Frozen organic strawberries and fruit sold throughout California were linked to a possible outbreak of Hepatitis A.

Claim B:
Affected lots and products in California include: Simply Nature Organic Strawberries - Best by June 14, 2024 Trader Joe's Organic Tropical Fruit Blend Pineapple, Bananas, Strawberries & Mango - Best by April 25, 2024/ May 12, 2024/ May 23, 2024/ May 30, 2024/ June 7, 2024 Kirkland Signature Organic Strawberries - Specific lot numbers in L.A., San Diego and Hawaii More Scenic Fruit Company products were recalled nationwide including: Vital Choice Organic Strawberries - Best by Oct. 8, 2024 - Alaska, Idaho, Montana, Oregon, Utah and Washington Made With Organic Strawberries - Best by Nov. 20, 2024 - Illinois, Maryland PCC Community Markets Organic Strawberries - Best by Oct. 29, 2024 - Washington Hepatitis A is a contagious liver disease.

=================================================================
Claims 21 & 22
Similarity: 0.8542

Claim A:
The FDA said that the illness can cause liver failure in people who have severe pre-existing illnesses.

Claim B:
The FDA said that the illness can cause liver failure in people who are immunocompromised.

=================================================================
Claims 19 & 20
Similarity: 0.8311

Claim A:
The illness can cause liver failure in people who have severe pre-existing illnesses.

Claim B:
The illness can cause liver failure in people who are immunocompromised.

=================================================================
Claims 19 & 22
Similarity: 0.8206

Claim A:
The illness can cause liver failure in people who have severe pre-existing illnesses.

Claim B:
The FDA said that the illness can cause liver failure in people who are immunocompromised.

=================================================================
Claims 1 & 3
Similarity: 0.8085

Claim A:
Fruit Sold In CA Recalled Due To Hepatitis A Outbreak Frozen organic strawberries and fruit sold throughout California were linked to a possible outbreak of Hepatitis A.

Claim B:
The FDA recalled two frozen strawberry and tropical fruit products sold in California recently.

=================================================================
Claims 20 & 21
Similarity: 0.7946

Claim A:
The illness can cause liver failure in people who are immunocompromised.

Claim B:
The FDA said that the illness can cause liver failure in people who have severe pre-existing illnesses.

=================================================================
Claims 2 & 17
Similarity: 0.7901

Claim A:
Different brands of frozen organic strawberries sold in California were linked to a recent Hepatitis A outbreak.

Claim B:
Affected lots and products in California include: Simply Nature Organic Strawberries - Best by June 14, 2024 Trader Joe's Organic Tropical Fruit Blend Pineapple, Bananas, Strawberries & Mango - Best by April 25, 2024/ May 12, 2024/ May 23, 2024/ May 30, 2024/ June 7, 2024 Kirkland Signature Organic Strawberries - Specific lot numbers in L.A., San Diego and Hawaii More Scenic Fruit Company products were recalled nationwide including: Vital Choice Organic Strawberries - Best by Oct. 8, 2024 - Alaska, Idaho, Montana, Oregon, Utah and Washington Made With Organic Strawberries - Best by Nov. 20, 2024 - Illinois, Maryland PCC Community Markets Organic Strawberries - Best by Oct. 29, 2024 - Washington Hepatitis A is a contagious liver disease.

=================================================================
Claims 3 & 6
Similarity: 0.7816

Claim A:
The FDA recalled two frozen strawberry and tropical fruit products sold in California recently.

Claim B:
California Splendor of San Diego recalled bags of their Kirkland Signature Frozen Organic Strawberries.

=================================================================
Claims 11 & 12
Similarity: 0.7783

Claim A:
The frozen organic strawberries were from a common supplier from certain farms in Baja California, Mexico.

Claim B:
The frozen organic strawberries were sold to a variety of retailers under multiple brand labels.

=================================================================
Claims 4 & 6
Similarity: 0.7712

Claim A:
Scenic Fruit Company of Gresham, Oregon recalled Simply Nature frozen organic strawberries sold in Aldi stores.

Claim B:
California Splendor of San Diego recalled bags of their Kirkland Signature Frozen Organic Strawberries.

=================================================================
Claims 1 & 15
Similarity: 0.7617

Claim A:
Fruit Sold In CA Recalled Due To Hepatitis A Outbreak Frozen organic strawberries and fruit sold throughout California were linked to a possible outbreak of Hepatitis A.

Claim B:
An identical strain of hepatitis in May 2022 was linked to frozen organic strawberries imported from Baja California.

In [16]:
PAIRWISE_PROMPT = """
You are evaluating semantic redundancy between two
factual claims extracted from a news article.

Determine whether the claims express substantially
the same factual information.

REDUNDANT:
Both claims communicate the same core factual assertion.
Keeping both adds little or no substantial information.

NOT_REDUNDANT:
The claims express distinct factual assertions, even
if they discuss the same topic or share many words.

Rules:
- Evaluate factual meaning, not word similarity.
- Different wording can express the same fact.
- Multiple entities or similar topics do not imply redundancy.
- Preserve meaningful differences in dates, numbers,
  negation, uncertainty, entities, and relationships.
- If one claim adds substantial new factual information,
  classify the pair as NOT_REDUNDANT.
- Do not assume the claims are redundant.
- Do not rewrite the claims.

Return ONLY valid JSON:
{
  "label": "REDUNDANT",
  "reason": "Brief explanation"
}
"""

In [17]:
import json

def evaluate_pair_qwen(claim_a, claim_b):

    response = llm.create_chat_completion(
        messages=[
            {
                "role": "system",
                "content": PAIRWISE_PROMPT
            },
            {
                "role": "user",
                "content": (
                    "/no_think\n"
                    f"CLAIM A: {claim_a}\n"
                    f"CLAIM B: {claim_b}"
                )
            }
        ],
        temperature=0,
        max_tokens=160,
        response_format={"type": "json_object"}
    )

    generated = response["choices"][0]["message"]["content"]

    result = json.loads(generated)

    if result.get("label") not in {
        "REDUNDANT", "NOT_REDUNDANT"
    }:
        raise ValueError(f"Unexpected label: {result}")

    return result

print("Pairwise redundancy evaluator ready!")

Pairwise redundancy evaluator ready!

In [18]:
pair_results = []

for _, row in pairs_df.head(15).iterrows():

    result = evaluate_pair_qwen(
        row["Claim 1"],
        row["Claim 2"]
    )

    pair_results.append({
        "Claim 1 ID": int(row["Claim 1 ID"]),
        "Claim 2 ID": int(row["Claim 2 ID"]),
        "SBERT Similarity": row["Similarity"],
        "Qwen Label": result["label"],
        "Reason": result.get("reason", "")
    })

pair_results_df = pd.DataFrame(pair_results)

display(pair_results_df)

Llama.generate: 8 prefix-match hit, remaining 237 prompt tokens to eval
ggml_cuda_graph_set_enabled: disabling CUDA graphs due to GPU architecture
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     483.18 ms /   237 tokens (    2.04 ms per token,   490.50 tokens per second)
llama_perf_context_print:        eval time =    1525.26 ms /    53 runs   (   28.78 ms per token,    34.75 tokens per second)
llama_perf_context_print:       total time =    4030.72 ms /   290 tokens
llama_perf_context_print:    graphs reused =         51
Llama.generate: 212 prefix-match hit, remaining 33 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     230.00 ms /    33 tokens (    6.97 ms per token,   143.48 tokens per second)
llama_perf_context_print:        eval time =    1496.22 ms /    52 runs   (   28.77 ms per token,    34.75 tokens per second)
llama_perf_context_print:       total time =    3703.17 ms /    85 tokens
llama_perf_context_print:    graphs reused =         50
Llama.generate: 203 prefix-match hit, remaining 59 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     241.79 ms /    59 tokens (    4.10 ms per token,   244.01 tokens per second)
llama_perf_context_print:        eval time =    1975.88 ms /    68 runs   (   29.06 ms per token,    34.41 tokens per second)
llama_perf_context_print:       total time =    4826.86 ms /   127 tokens
llama_perf_context_print:    graphs reused =         67
Llama.generate: 203 prefix-match hit, remaining 51 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     235.77 ms /    51 tokens (    4.62 ms per token,   216.32 tokens per second)
llama_perf_context_print:        eval time =    2206.08 ms /    76 runs   (   29.03 ms per token,    34.45 tokens per second)
llama_perf_context_print:       total time =    5351.09 ms /   127 tokens
llama_perf_context_print:    graphs reused =         74
Llama.generate: 203 prefix-match hit, remaining 254 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     485.53 ms /   254 tokens (    1.91 ms per token,   523.15 tokens per second)
llama_perf_context_print:        eval time =    2163.06 ms /    74 runs   (   29.23 ms per token,    34.21 tokens per second)
llama_perf_context_print:       total time =    5489.99 ms /   328 tokens
llama_perf_context_print:    graphs reused =         72
Llama.generate: 203 prefix-match hit, remaining 46 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     234.60 ms /    46 tokens (    5.10 ms per token,   196.08 tokens per second)
llama_perf_context_print:        eval time =    1589.34 ms /    55 runs   (   28.90 ms per token,    34.61 tokens per second)
llama_perf_context_print:       total time =    3928.63 ms /   101 tokens
llama_perf_context_print:    graphs reused =         53
Llama.generate: 204 prefix-match hit, remaining 37 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     231.55 ms /    37 tokens (    6.26 ms per token,   159.79 tokens per second)
llama_perf_context_print:        eval time =    1287.35 ms /    45 runs   (   28.61 ms per token,    34.96 tokens per second)
llama_perf_context_print:       total time =    3238.99 ms /    82 tokens
llama_perf_context_print:    graphs reused =         43
Llama.generate: 222 prefix-match hit, remaining 23 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     226.88 ms /    23 tokens (    9.86 ms per token,   101.37 tokens per second)
llama_perf_context_print:        eval time =    1525.61 ms /    53 runs   (   28.79 ms per token,    34.74 tokens per second)
llama_perf_context_print:       total time =    3790.81 ms /    76 tokens
llama_perf_context_print:    graphs reused =         51
Llama.generate: 203 prefix-match hit, remaining 55 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     239.83 ms /    55 tokens (    4.36 ms per token,   229.33 tokens per second)
llama_perf_context_print:        eval time =    1482.53 ms /    51 runs   (   29.07 ms per token,    34.40 tokens per second)
llama_perf_context_print:       total time =    3685.82 ms /   106 tokens
llama_perf_context_print:    graphs reused =         50
Llama.generate: 203 prefix-match hit, remaining 42 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     232.97 ms /    42 tokens (    5.55 ms per token,   180.28 tokens per second)
llama_perf_context_print:        eval time =    2309.66 ms /    80 runs   (   28.87 ms per token,    34.64 tokens per second)
llama_perf_context_print:       total time =    5644.28 ms /   122 tokens
llama_perf_context_print:    graphs reused =         78
Llama.generate: 203 prefix-match hit, remaining 241 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     479.26 ms /   241 tokens (    1.99 ms per token,   502.86 tokens per second)
llama_perf_context_print:        eval time =    2511.73 ms /    86 runs   (   29.21 ms per token,    34.24 tokens per second)
llama_perf_context_print:       total time =    6318.80 ms /   327 tokens
llama_perf_context_print:    graphs reused =         84
Llama.generate: 203 prefix-match hit, remaining 41 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     232.67 ms /    41 tokens (    5.67 ms per token,   176.22 tokens per second)
llama_perf_context_print:        eval time =    1960.28 ms /    68 runs   (   28.83 ms per token,    34.69 tokens per second)
llama_perf_context_print:       total time =    4833.20 ms /   109 tokens
llama_perf_context_print:    graphs reused =         66
Llama.generate: 204 prefix-match hit, remaining 42 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     233.16 ms /    42 tokens (    5.55 ms per token,   180.13 tokens per second)
llama_perf_context_print:        eval time =    1759.74 ms /    61 runs   (   28.85 ms per token,    34.66 tokens per second)
llama_perf_context_print:       total time =    4374.47 ms /   103 tokens
llama_perf_context_print:    graphs reused =         59
Llama.generate: 203 prefix-match hit, remaining 48 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     235.04 ms /    48 tokens (    4.90 ms per token,   204.22 tokens per second)
llama_perf_context_print:        eval time =    1853.67 ms /    64 runs   (   28.96 ms per token,    34.53 tokens per second)
llama_perf_context_print:       total time =    4498.27 ms /   112 tokens
llama_perf_context_print:    graphs reused =         62
Llama.generate: 203 prefix-match hit, remaining 64 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     243.55 ms /    64 tokens (    3.81 ms per token,   262.78 tokens per second)
llama_perf_context_print:        eval time =    2295.61 ms /    79 runs   (   29.06 ms per token,    34.41 tokens per second)
llama_perf_context_print:       total time =    5527.52 ms /   143 tokens
llama_perf_context_print:    graphs reused =         78

,Claim 1 ID,Claim 2 ID,SBERT Similarity,Qwen Label,Reason
0,19,21,0.961154,REDUNDANT,Both claims state the same factual assertion a...
1,20,22,0.959762,REDUNDANT,Both claims state the same factual assertion a...
2,1,2,0.883355,NOT_REDUNDANT,Claim A mentions the recall due to Hepatitis A...
3,2,15,0.868105,NOT_REDUNDANT,Claim A attributes the outbreak to different b...
4,1,17,0.859105,NOT_REDUNDANT,Claim A discusses a general recall of fruit in...
5,21,22,0.854232,NOT_REDUNDANT,The claims differ in the specific group affect...
6,19,20,0.831124,NOT_REDUNDANT,The claims differ in the specific condition de...
7,19,22,0.820556,NOT_REDUNDANT,Claim A refers to 'severe pre-existing illness...
8,1,3,0.808464,NOT_REDUNDANT,Claim A specifies the outbreak is due to Hepat...
9,20,21,0.794553,NOT_REDUNDANT,Claim A states the illness can cause liver fai...
10,2,17,0.790072,NOT_REDUNDANT,Claim A states that different brands of frozen...
11,3,6,0.781593,NOT_REDUNDANT,Claim A mentions a recall of two frozen strawb...
12,11,12,0.778286,NOT_REDUNDANT,Claim A specifies the origin of the strawberri...
13,4,6,0.771233,NOT_REDUNDANT,The claims mention different companies (Scenic...
14,1,15,0.761735,NOT_REDUNDANT,Claim A mentions a Hepatitis A outbreak linked...

In [19]:
THRESHOLD = 0.70

candidate_pairs = pairs_df[
    pairs_df["Similarity"] >= THRESHOLD
].copy()

print("Total possible pairs:", len(pairs_df))
print("Candidate pairs:", len(candidate_pairs))

display(
    candidate_pairs[
        ["Claim 1 ID", "Claim 2 ID", "Similarity"]
    ]
)

Total possible pairs: 231
Candidate pairs: 21

    Claim 1 ID  Claim 2 ID  Similarity
0           19          21    0.961154
1           20          22    0.959762
2            1           2    0.883355
3            2          15    0.868105
4            1          17    0.859105
5           21          22    0.854232
6           19          20    0.831124
7           19          22    0.820556
8            1           3    0.808464
9           20          21    0.794553
10           2          17    0.790072
11           3           6    0.781593
12          11          12    0.778286
13           4           6    0.771233
14           1          15    0.761735
15           4          17    0.748337
16           3           4    0.747503
17           4           5    0.747274
18           6          17    0.747105
19           3          17    0.745597
20           1           6    0.707312

In [20]:
# Find pairs we already evaluated
evaluated_pairs = set(
    zip(
        pair_results_df["Claim 1 ID"],
        pair_results_df["Claim 2 ID"]
    )
)

# Keep only pairs not yet evaluated
remaining_pairs = candidate_pairs[
    ~candidate_pairs.apply(
        lambda row: (
            row["Claim 1 ID"],
            row["Claim 2 ID"]
        ) in evaluated_pairs,
        axis=1
    )
]

print("Remaining pairs:", len(remaining_pairs))

new_results = []

for _, row in remaining_pairs.iterrows():

    result = evaluate_pair_qwen(
        row["Claim 1"],
        row["Claim 2"]
    )

    new_results.append({
        "Claim 1 ID": int(row["Claim 1 ID"]),
        "Claim 2 ID": int(row["Claim 2 ID"]),
        "SBERT Similarity": row["Similarity"],
        "Qwen Label": result["label"],
        "Reason": result.get("reason", "")
    })

new_results_df = pd.DataFrame(new_results)

display(new_results_df)

Llama.generate: 203 prefix-match hit, remaining 244 prompt tokens to eval
ggml_cuda_graph_set_enabled: disabling CUDA graphs due to GPU architecture

Remaining pairs: 6

llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     488.97 ms /   244 tokens (    2.00 ms per token,   499.01 tokens per second)
llama_perf_context_print:        eval time =    2305.72 ms /    79 runs   (   29.19 ms per token,    34.26 tokens per second)
llama_perf_context_print:       total time =    5833.82 ms /   323 tokens
llama_perf_context_print:    graphs reused =         77
Llama.generate: 203 prefix-match hit, remaining 45 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     233.90 ms /    45 tokens (    5.20 ms per token,   192.39 tokens per second)
llama_perf_context_print:        eval time =    2081.97 ms /    72 runs   (   28.92 ms per token,    34.58 tokens per second)
llama_perf_context_print:       total time =    5071.08 ms /   117 tokens
llama_perf_context_print:    graphs reused =         70
Llama.generate: 203 prefix-match hit, remaining 59 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     242.06 ms /    59 tokens (    4.10 ms per token,   243.74 tokens per second)
llama_perf_context_print:        eval time =    1221.47 ms /    42 runs   (   29.08 ms per token,    34.38 tokens per second)
llama_perf_context_print:       total time =    3074.01 ms /   101 tokens
llama_perf_context_print:    graphs reused =         41
Llama.generate: 203 prefix-match hit, remaining 240 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     479.24 ms /   240 tokens (    2.00 ms per token,   500.79 tokens per second)
llama_perf_context_print:        eval time =    2421.41 ms /    83 runs   (   29.17 ms per token,    34.28 tokens per second)
llama_perf_context_print:       total time =    6083.73 ms /   323 tokens
llama_perf_context_print:    graphs reused =         81
Llama.generate: 203 prefix-match hit, remaining 237 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     478.04 ms /   237 tokens (    2.02 ms per token,   495.77 tokens per second)
llama_perf_context_print:        eval time =    2063.38 ms /    71 runs   (   29.06 ms per token,    34.41 tokens per second)
llama_perf_context_print:       total time =    5265.90 ms /   308 tokens
llama_perf_context_print:    graphs reused =         70
Llama.generate: 203 prefix-match hit, remaining 58 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     241.15 ms /    58 tokens (    4.16 ms per token,   240.51 tokens per second)
llama_perf_context_print:        eval time =    1657.14 ms /    57 runs   (   29.07 ms per token,    34.40 tokens per second)
llama_perf_context_print:       total time =    4107.79 ms /   115 tokens
llama_perf_context_print:    graphs reused =         56

,Claim 1 ID,Claim 2 ID,SBERT Similarity,Qwen Label,Reason
0,4,17,0.748337,NOT_REDUNDANT,Claim A focuses on a specific recall of Simply...
1,3,4,0.747503,NOT_REDUNDANT,Claim A mentions a recall of two frozen strawb...
2,4,5,0.747274,NOT_REDUNDANT,The claims mention different products (strawbe...
3,6,17,0.747105,NOT_REDUNDANT,Claim A mentions a specific product (Kirkland ...
4,3,17,0.745597,NOT_REDUNDANT,Claim A mentions a recall of two frozen fruit ...
5,1,6,0.707312,NOT_REDUNDANT,Claim A discusses a broader recall involving m...

In [21]:
all_pair_results_df = pd.concat(
    [pair_results_df, new_results_df],
    ignore_index=True
)

print("Total evaluated pairs:", len(all_pair_results_df))

print("\nQwen label counts:")
print(all_pair_results_df["Qwen Label"].value_counts())

print("\nRedundant pairs:")
display(
    all_pair_results_df[
        all_pair_results_df["Qwen Label"] == "REDUNDANT"
    ]
)

Total evaluated pairs: 21

Qwen label counts:
Qwen Label
NOT_REDUNDANT    19
REDUNDANT         2
Name: count, dtype: int64

Redundant pairs:

,Claim 1 ID,Claim 2 ID,SBERT Similarity,Qwen Label,Reason
0,19,21,0.961154,REDUNDANT,Both claims state the same factual assertion a...
1,20,22,0.959762,REDUNDANT,Both claims state the same factual assertion a...

In [22]:
all_pair_results_df.to_csv(
    "qwen_redundancy_pairs_article_6_1.csv",
    index=False
)

print("Saved successfully!")

Saved successfully!

**Since it ran for 1 article, now running it for all 30 articles in the validation set**

In [23]:
import pandas as pd
import numpy as np
import json
import time
from pathlib import Path
from sentence_transformers import util

# Check that existing objects are available
print("Claims loaded:", "claims_df" in globals())
print("SBERT loaded:", "sbert" in globals())
print("Qwen loaded:", "llm" in globals())
print("Pairwise evaluator ready:",
      "evaluate_pair_qwen" in globals())

print("Total claims:", len(claims_df))
print("Total articles:",
      claims_df.groupby(["event_id", "article_id"]).ngroups)

Claims loaded: True
SBERT loaded: True
Qwen loaded: True
Pairwise evaluator ready: True
Total claims: 1014
Total articles: 30

In [24]:
RESULTS_DIR = Path(
    "/project2/xiangren_1987/group_22/redundancy_results"
)

RESULTS_DIR.mkdir(parents=True, exist_ok=True)

THRESHOLD = 0.70

ARTICLE_FILE = RESULTS_DIR / "redundancy_by_article.csv"
PAIRS_FILE = RESULTS_DIR / "redundancy_pairs.csv"
SUMMARY_FILE = RESULTS_DIR / "redundancy_summary.csv"

print("Results directory:", RESULTS_DIR)
print("SBERT threshold:", THRESHOLD)

Results directory: /project2/xiangren_1987/group_22/redundancy_results
SBERT threshold: 0.7

In [25]:
def evaluate_article(event_id, article_id, group_df):

    claims = group_df["claim"].tolist()
    n = len(claims)

    # Generate SBERT embeddings
    embeddings = sbert.encode(
        claims,
        convert_to_tensor=True,
        normalize_embeddings=True,
        show_progress_bar=False
    )

    similarity_matrix = util.cos_sim(
        embeddings, embeddings
    ).cpu().numpy()

    pair_records = []

    # Evaluate only candidate pairs above threshold
    for i in range(n):
        for j in range(i + 1, n):

            similarity = float(similarity_matrix[i, j])

            if similarity < THRESHOLD:
                continue

            result = evaluate_pair_qwen(
                claims[i],
                claims[j]
            )

            pair_records.append({
                "event_id": event_id,
                "article_id": article_id,
                "claim_1_id": i + 1,
                "claim_2_id": j + 1,
                "claim_1": claims[i],
                "claim_2": claims[j],
                "sbert_similarity": similarity,
                "qwen_label": result["label"],
                "reason": result.get("reason", "")
            })

    # Build connected components of redundant claims
    parent = list(range(n))

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(a, b):
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[rb] = ra

    for record in pair_records:
        if record["qwen_label"] == "REDUNDANT":
            union(
                record["claim_1_id"] - 1,
                record["claim_2_id"] - 1
            )

    clusters = {}

    for i in range(n):
        root = find(i)
        clusters.setdefault(root, []).append(i + 1)

    duplicate_groups = [
        members
        for members in clusters.values()
        if len(members) > 1
    ]

    redundant_copies = sum(
        len(group) - 1
        for group in duplicate_groups
    )

    article_result = {
        "event_id": event_id,
        "article_id": article_id,
        "total_claims": n,
        "candidate_pairs": len(pair_records),
        "redundant_pairs": sum(
            r["qwen_label"] == "REDUNDANT"
            for r in pair_records
        ),
        "duplicate_groups": json.dumps(duplicate_groups),
        "redundant_copies": redundant_copies,
        "redundancy_rate": redundant_copies / n if n else 0,
        "status": "OK"
    }

    return article_result, pair_records

print("Article evaluation function ready!")

Article evaluation function ready!

In [26]:
# Load previous progress if available
if ARTICLE_FILE.exists():
    article_results_df = pd.read_csv(ARTICLE_FILE)
    print("Loaded previous article results.")
else:
    article_results_df = pd.DataFrame()

if PAIRS_FILE.exists():
    all_pairs_df = pd.read_csv(PAIRS_FILE)
    print("Loaded previous pair results.")
else:
    all_pairs_df = pd.DataFrame()

grouped = claims_df.groupby(
    ["event_id", "article_id"],
    sort=False
)

total_articles = grouped.ngroups

for idx, ((event_id, article_id), group_df) in enumerate(grouped, 1):

    # Skip successfully completed articles
    if not article_results_df.empty:
        completed = (
            (article_results_df["event_id"] == event_id) &
            (article_results_df["article_id"] == article_id) &
            (article_results_df["status"] == "OK")
        )

        if completed.any():
            print(f"Skipping completed article {idx}/{total_articles}")
            continue

    print(f"\nEvaluating article {idx}/{total_articles}")
    print("Event:", event_id, "Article:", article_id)

    start = time.time()

    try:
        article_result, pair_records = evaluate_article(
            event_id,
            article_id,
            group_df
        )

        # Replace any previous failed attempt
        if not article_results_df.empty:
            mask = (
                (article_results_df["event_id"] == event_id) &
                (article_results_df["article_id"] == article_id)
            )
            article_results_df = article_results_df.loc[~mask]

        article_results_df = pd.concat(
            [article_results_df, pd.DataFrame([article_result])],
            ignore_index=True
        )

        if pair_records:
            new_pairs = pd.DataFrame(pair_records)

            if not all_pairs_df.empty:
                mask = (
                    (all_pairs_df["event_id"] == event_id) &
                    (all_pairs_df["article_id"] == article_id)
                )
                all_pairs_df = all_pairs_df.loc[~mask]

            all_pairs_df = pd.concat(
                [all_pairs_df, new_pairs],
                ignore_index=True
            )

        # Save progress after every article
        article_results_df.to_csv(ARTICLE_FILE, index=False)
        all_pairs_df.to_csv(PAIRS_FILE, index=False)

        print("Claims:", article_result["total_claims"])
        print("Candidate pairs:", article_result["candidate_pairs"])
        print("Redundant copies:", article_result["redundant_copies"])
        print(f"Redundancy: {article_result['redundancy_rate']:.2%}")

    except Exception as e:
        print("FAILED:", str(e))

        error_result = {
            "event_id": event_id,
            "article_id": article_id,
            "total_claims": len(group_df),
            "candidate_pairs": None,
            "redundant_pairs": None,
            "duplicate_groups": None,
            "redundant_copies": None,
            "redundancy_rate": None,
            "status": f"ERROR: {str(e)[:200]}"
        }

        if not article_results_df.empty:
            mask = (
                (article_results_df["event_id"] == event_id) &
                (article_results_df["article_id"] == article_id)
            )
            article_results_df = article_results_df.loc[~mask]

        article_results_df = pd.concat(
            [article_results_df, pd.DataFrame([error_result])],
            ignore_index=True
        )

        article_results_df.to_csv(ARTICLE_FILE, index=False)

    print("Elapsed seconds:", round(time.time() - start, 1))

print("\nEvaluation loop finished!")
print(article_results_df["status"].value_counts())

Evaluating article 1/30
Event: 6 Article: 6.1

Llama.generate: 238 prefix-match hit, remaining 24 prompt tokens to eval
ggml_cuda_graph_set_enabled: disabling CUDA graphs due to GPU architecture
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     247.24 ms /    24 tokens (   10.30 ms per token,    97.07 tokens per second)
llama_perf_context_print:        eval time =    1976.32 ms /    68 runs   (   29.06 ms per token,    34.41 tokens per second)
llama_perf_context_print:       total time =    4719.83 ms /    92 tokens
llama_perf_context_print:    graphs reused =         67
Llama.generate: 238 prefix-match hit, remaining 20 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     227.83 ms /    20 tokens (   11.39 ms per token,    87.79 tokens per second)
llama_perf_context_print:        eval time =    1481.84 ms /    51 runs   (   29.06 ms per token,    34.42 tokens per second)
llama_perf_context_print:       total time =    3561.27 ms /    71 tokens
llama_perf_context_print:    graphs reused =         50
Llama.generate: 238 prefix-match hit, remaining 23 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     229.02 ms /    23 tokens (    9.96 ms per token,   100.43 tokens per second)
llama_perf_context_print:        eval time =    1655.80 ms /    57 runs   (   29.05 ms per token,    34.42 tokens per second)
llama_perf_context_print:       total time =    3976.06 ms /    80 tokens
llama_perf_context_print:    graphs reused =         56
Llama.generate: 238 prefix-match hit, remaining 29 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     230.64 ms /    29 tokens (    7.95 ms per token,   125.74 tokens per second)
llama_perf_context_print:        eval time =    2294.80 ms /    79 runs   (   29.05 ms per token,    34.43 tokens per second)
llama_perf_context_print:       total time =    5436.99 ms /   108 tokens
llama_perf_context_print:    graphs reused =         78
Llama.generate: 238 prefix-match hit, remaining 219 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     472.91 ms /   219 tokens (    2.16 ms per token,   463.09 tokens per second)
llama_perf_context_print:        eval time =    2162.18 ms /    74 runs   (   29.22 ms per token,    34.22 tokens per second)
llama_perf_context_print:       total time =    5366.03 ms /   293 tokens
llama_perf_context_print:    graphs reused =         72
Llama.generate: 203 prefix-match hit, remaining 51 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     235.51 ms /    51 tokens (    4.62 ms per token,   216.55 tokens per second)
llama_perf_context_print:        eval time =    2206.50 ms /    76 runs   (   29.03 ms per token,    34.44 tokens per second)
llama_perf_context_print:       total time =    5249.52 ms /   127 tokens
llama_perf_context_print:    graphs reused =         74
Llama.generate: 225 prefix-match hit, remaining 219 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     472.56 ms /   219 tokens (    2.16 ms per token,   463.43 tokens per second)
llama_perf_context_print:        eval time =    2510.34 ms /    86 runs   (   29.19 ms per token,    34.26 tokens per second)
llama_perf_context_print:       total time =    6163.49 ms /   305 tokens
llama_perf_context_print:    graphs reused =         84
Llama.generate: 203 prefix-match hit, remaining 45 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     233.84 ms /    45 tokens (    5.20 ms per token,   192.44 tokens per second)
llama_perf_context_print:        eval time =    2081.34 ms /    72 runs   (   28.91 ms per token,    34.59 tokens per second)
llama_perf_context_print:       total time =    4987.51 ms /   117 tokens
llama_perf_context_print:    graphs reused =         70
Llama.generate: 221 prefix-match hit, remaining 23 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     226.73 ms /    23 tokens (    9.86 ms per token,   101.44 tokens per second)
llama_perf_context_print:        eval time =    1959.68 ms /    68 runs   (   28.82 ms per token,    34.70 tokens per second)
llama_perf_context_print:       total time =    4702.22 ms /    91 tokens
llama_perf_context_print:    graphs reused =         66
Llama.generate: 221 prefix-match hit, remaining 219 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     472.91 ms /   219 tokens (    2.16 ms per token,   463.09 tokens per second)
llama_perf_context_print:        eval time =    2063.68 ms /    71 runs   (   29.07 ms per token,    34.40 tokens per second)
llama_perf_context_print:       total time =    5162.10 ms /   290 tokens
llama_perf_context_print:    graphs reused =         70
Llama.generate: 203 prefix-match hit, remaining 59 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     241.58 ms /    59 tokens (    4.09 ms per token,   244.23 tokens per second)
llama_perf_context_print:        eval time =    1221.22 ms /    42 runs   (   29.08 ms per token,    34.39 tokens per second)
llama_perf_context_print:       total time =    3033.53 ms /   101 tokens
llama_perf_context_print:    graphs reused =         41
Llama.generate: 228 prefix-match hit, remaining 23 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     226.75 ms /    23 tokens (    9.86 ms per token,   101.43 tokens per second)
llama_perf_context_print:        eval time =    1853.57 ms /    64 runs   (   28.96 ms per token,    34.53 tokens per second)
llama_perf_context_print:       total time =    4473.64 ms /    87 tokens
llama_perf_context_print:    graphs reused =         62
Llama.generate: 228 prefix-match hit, remaining 219 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     472.57 ms /   219 tokens (    2.16 ms per token,   463.42 tokens per second)
llama_perf_context_print:        eval time =    2304.93 ms /    79 runs   (   29.18 ms per token,    34.27 tokens per second)
llama_perf_context_print:       total time =    5724.08 ms /   298 tokens
llama_perf_context_print:    graphs reused =         77
Llama.generate: 203 prefix-match hit, remaining 240 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     478.31 ms /   240 tokens (    1.99 ms per token,   501.77 tokens per second)
llama_perf_context_print:        eval time =    2420.80 ms /    83 runs   (   29.17 ms per token,    34.29 tokens per second)
llama_perf_context_print:       total time =    5985.76 ms /   323 tokens
llama_perf_context_print:    graphs reused =         81
Llama.generate: 203 prefix-match hit, remaining 43 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     233.37 ms /    43 tokens (    5.43 ms per token,   184.25 tokens per second)
llama_perf_context_print:        eval time =    1759.12 ms /    61 runs   (   28.84 ms per token,    34.68 tokens per second)
llama_perf_context_print:       total time =    4269.33 ms /   104 tokens
llama_perf_context_print:    graphs reused =         59
Llama.generate: 204 prefix-match hit, remaining 37 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     231.21 ms /    37 tokens (    6.25 ms per token,   160.03 tokens per second)
llama_perf_context_print:        eval time =    1287.64 ms /    45 runs   (   28.61 ms per token,    34.95 tokens per second)
llama_perf_context_print:       total time =    3204.29 ms /    82 tokens
llama_perf_context_print:    graphs reused =         43
Llama.generate: 222 prefix-match hit, remaining 23 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     226.86 ms /    23 tokens (    9.86 ms per token,   101.38 tokens per second)
llama_perf_context_print:        eval time =    1525.62 ms /    53 runs   (   28.79 ms per token,    34.74 tokens per second)
llama_perf_context_print:       total time =    3745.78 ms /    76 tokens
llama_perf_context_print:    graphs reused =         51
Llama.generate: 234 prefix-match hit, remaining 11 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     260.87 ms /    11 tokens (   23.72 ms per token,    42.17 tokens per second)
llama_perf_context_print:        eval time =    1525.17 ms /    53 runs   (   28.78 ms per token,    34.75 tokens per second)
llama_perf_context_print:       total time =    3770.73 ms /    64 tokens
llama_perf_context_print:    graphs reused =         51
Llama.generate: 212 prefix-match hit, remaining 33 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     229.94 ms /    33 tokens (    6.97 ms per token,   143.52 tokens per second)
llama_perf_context_print:        eval time =    2309.73 ms /    80 runs   (   28.87 ms per token,    34.64 tokens per second)
llama_perf_context_print:       total time =    5536.96 ms /   113 tokens
llama_perf_context_print:    graphs reused =         78
Llama.generate: 234 prefix-match hit, remaining 11 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     224.52 ms /    11 tokens (   20.41 ms per token,    48.99 tokens per second)
llama_perf_context_print:        eval time =    1496.47 ms /    52 runs   (   28.78 ms per token,    34.75 tokens per second)
llama_perf_context_print:       total time =    3674.13 ms /    63 tokens
llama_perf_context_print:    graphs reused =         50
Llama.generate: 204 prefix-match hit, remaining 45 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     233.83 ms /    45 tokens (    5.20 ms per token,   192.45 tokens per second)
llama_perf_context_print:        eval time =    1589.64 ms /    55 runs   (   28.90 ms per token,    34.60 tokens per second)
llama_perf_context_print:       total time =    3903.14 ms /   100 tokens
llama_perf_context_print:    graphs reused =         53

Claims: 22
Candidate pairs: 21
Redundant copies: 2
Redundancy: 9.09%
Elapsed seconds: 99.3

Evaluating article 2/30
Event: 6 Article: 6.4

Llama.generate: 203 prefix-match hit, remaining 41 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     243.14 ms /    41 tokens (    5.93 ms per token,   168.63 tokens per second)
llama_perf_context_print:        eval time =    1407.41 ms /    49 runs   (   28.72 ms per token,    34.82 tokens per second)
llama_perf_context_print:       total time =    3431.43 ms /    90 tokens
llama_perf_context_print:    graphs reused =         47
Llama.generate: 203 prefix-match hit, remaining 32 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     229.50 ms /    32 tokens (    7.17 ms per token,   139.43 tokens per second)
llama_perf_context_print:        eval time =    1683.98 ms /    59 runs   (   28.54 ms per token,    35.04 tokens per second)
llama_perf_context_print:       total time =    4063.73 ms /    91 tokens
llama_perf_context_print:    graphs reused =         57

Claims: 22
Candidate pairs: 2
Redundant copies: 1
Redundancy: 4.55%
Elapsed seconds: 11.7

Evaluating article 3/30
Event: 6 Article: 6.5

Llama.generate: 203 prefix-match hit, remaining 56 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     240.23 ms /    56 tokens (    4.29 ms per token,   233.11 tokens per second)
llama_perf_context_print:        eval time =    1365.77 ms /    47 runs   (   29.06 ms per token,    34.41 tokens per second)
llama_perf_context_print:       total time =    3364.12 ms /   103 tokens
llama_perf_context_print:    graphs reused =         46
Llama.generate: 203 prefix-match hit, remaining 52 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     236.23 ms /    52 tokens (    4.54 ms per token,   220.12 tokens per second)
llama_perf_context_print:        eval time =    1278.22 ms /    44 runs   (   29.05 ms per token,    34.42 tokens per second)
llama_perf_context_print:       total time =    3190.55 ms /    96 tokens
llama_perf_context_print:    graphs reused =         42

Claims: 24
Candidate pairs: 2
Redundant copies: 0
Redundancy: 0.00%
Elapsed seconds: 9.0

Evaluating article 4/30
Event: 6 Article: 6.8

Llama.generate: 203 prefix-match hit, remaining 42 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     233.06 ms /    42 tokens (    5.55 ms per token,   180.21 tokens per second)
llama_perf_context_print:        eval time =    2018.70 ms /    70 runs   (   28.84 ms per token,    34.68 tokens per second)
llama_perf_context_print:       total time =    4987.80 ms /   112 tokens
llama_perf_context_print:    graphs reused =         68
Llama.generate: 222 prefix-match hit, remaining 22 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     226.50 ms /    22 tokens (   10.30 ms per token,    97.13 tokens per second)
llama_perf_context_print:        eval time =    2656.13 ms /    92 runs   (   28.87 ms per token,    34.64 tokens per second)
llama_perf_context_print:       total time =    6449.02 ms /   114 tokens
llama_perf_context_print:    graphs reused =         90
Llama.generate: 203 prefix-match hit, remaining 55 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     239.82 ms /    55 tokens (    4.36 ms per token,   229.33 tokens per second)
llama_perf_context_print:        eval time =    1511.18 ms /    52 runs   (   29.06 ms per token,    34.41 tokens per second)
llama_perf_context_print:       total time =    3749.26 ms /   107 tokens
llama_perf_context_print:    graphs reused =         51
Llama.generate: 203 prefix-match hit, remaining 39 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     232.12 ms /    39 tokens (    5.95 ms per token,   168.01 tokens per second)
llama_perf_context_print:        eval time =    2247.04 ms /    78 runs   (   28.81 ms per token,    34.71 tokens per second)
llama_perf_context_print:       total time =    5493.77 ms /   117 tokens
llama_perf_context_print:    graphs reused =         76
Llama.generate: 203 prefix-match hit, remaining 57 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     240.95 ms /    57 tokens (    4.23 ms per token,   236.56 tokens per second)
llama_perf_context_print:        eval time =    2151.10 ms /    74 runs   (   29.07 ms per token,    34.40 tokens per second)
llama_perf_context_print:       total time =    5268.14 ms /   131 tokens
llama_perf_context_print:    graphs reused =         73
Llama.generate: 259 prefix-match hit, remaining 1 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =       0.00 ms /     1 tokens (    0.00 ms per token,      inf tokens per second)
llama_perf_context_print:        eval time =    2178.65 ms /    75 runs   (   29.05 ms per token,    34.43 tokens per second)
llama_perf_context_print:       total time =    5051.95 ms /    76 tokens
llama_perf_context_print:    graphs reused =         75
Llama.generate: 211 prefix-match hit, remaining 72 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     310.08 ms /    72 tokens (    4.31 ms per token,   232.20 tokens per second)
llama_perf_context_print:        eval time =     669.49 ms /    23 runs   (   29.11 ms per token,    34.35 tokens per second)
llama_perf_context_print:       total time =    1844.53 ms /    95 tokens
llama_perf_context_print:    graphs reused =         22
Llama.generate: 203 prefix-match hit, remaining 43 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     233.52 ms /    43 tokens (    5.43 ms per token,   184.14 tokens per second)
llama_perf_context_print:        eval time =    1265.54 ms /    44 runs   (   28.76 ms per token,    34.77 tokens per second)
llama_perf_context_print:       total time =    3136.03 ms /    87 tokens
llama_perf_context_print:    graphs reused =         42

Claims: 19
Candidate pairs: 8
Redundant copies: 2
Redundancy: 10.53%
Elapsed seconds: 38.3

Evaluating article 5/30
Event: 6 Article: 6.7

Llama.generate: 203 prefix-match hit, remaining 36 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     230.96 ms /    36 tokens (    6.42 ms per token,   155.87 tokens per second)
llama_perf_context_print:        eval time =    1980.22 ms /    69 runs   (   28.70 ms per token,    34.84 tokens per second)
llama_perf_context_print:       total time =    4738.14 ms /   105 tokens
llama_perf_context_print:    graphs reused =         67
Llama.generate: 217 prefix-match hit, remaining 36 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     231.16 ms /    36 tokens (    6.42 ms per token,   155.74 tokens per second)
llama_perf_context_print:        eval time =    1536.23 ms /    53 runs   (   28.99 ms per token,    34.50 tokens per second)
llama_perf_context_print:       total time =    3700.71 ms /    89 tokens
llama_perf_context_print:    graphs reused =         51
Llama.generate: 217 prefix-match hit, remaining 38 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     231.65 ms /    38 tokens (    6.10 ms per token,   164.04 tokens per second)
llama_perf_context_print:        eval time =    2177.41 ms /    75 runs   (   29.03 ms per token,    34.44 tokens per second)
llama_perf_context_print:       total time =    5179.63 ms /   113 tokens
llama_perf_context_print:    graphs reused =         73
Llama.generate: 205 prefix-match hit, remaining 54 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     239.43 ms /    54 tokens (    4.43 ms per token,   225.54 tokens per second)
llama_perf_context_print:        eval time =    1975.77 ms /    68 runs   (   29.06 ms per token,    34.42 tokens per second)
llama_perf_context_print:       total time =    4766.08 ms /   122 tokens
llama_perf_context_print:    graphs reused =         67
Llama.generate: 223 prefix-match hit, remaining 38 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     234.04 ms /    38 tokens (    6.16 ms per token,   162.37 tokens per second)
llama_perf_context_print:        eval time =    2323.81 ms /    80 runs   (   29.05 ms per token,    34.43 tokens per second)
llama_perf_context_print:       total time =    5652.61 ms /   118 tokens
llama_perf_context_print:    graphs reused =         79
Llama.generate: 203 prefix-match hit, remaining 65 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     307.69 ms /    65 tokens (    4.73 ms per token,   211.25 tokens per second)
llama_perf_context_print:        eval time =    1540.52 ms /    53 runs   (   29.07 ms per token,    34.40 tokens per second)
llama_perf_context_print:       total time =    3896.50 ms /   118 tokens
llama_perf_context_print:    graphs reused =         52
Llama.generate: 237 prefix-match hit, remaining 38 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     233.80 ms /    38 tokens (    6.15 ms per token,   162.53 tokens per second)
llama_perf_context_print:        eval time =    1859.56 ms /    64 runs   (   29.06 ms per token,    34.42 tokens per second)
llama_perf_context_print:       total time =    4578.39 ms /   102 tokens
llama_perf_context_print:    graphs reused =         63
Llama.generate: 203 prefix-match hit, remaining 52 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     236.10 ms /    52 tokens (    4.54 ms per token,   220.24 tokens per second)
llama_perf_context_print:        eval time =    1599.14 ms /    55 runs   (   29.08 ms per token,    34.39 tokens per second)
llama_perf_context_print:       total time =    3964.69 ms /   107 tokens
llama_perf_context_print:    graphs reused =         53

Claims: 26
Candidate pairs: 8
Redundant copies: 0
Redundancy: 0.00%
Elapsed seconds: 38.4

Evaluating article 6/30
Event: 20 Article: 20.3

Llama.generate: 203 prefix-match hit, remaining 44 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     233.93 ms /    44 tokens (    5.32 ms per token,   188.09 tokens per second)
llama_perf_context_print:        eval time =    1179.39 ms /    41 runs   (   28.77 ms per token,    34.76 tokens per second)
llama_perf_context_print:       total time =    2971.88 ms /    85 tokens
llama_perf_context_print:    graphs reused =         39
Llama.generate: 229 prefix-match hit, remaining 22 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     226.62 ms /    22 tokens (   10.30 ms per token,    97.08 tokens per second)
llama_perf_context_print:        eval time =    1185.52 ms /    41 runs   (   28.92 ms per token,    34.58 tokens per second)
llama_perf_context_print:       total time =    2978.57 ms /    63 tokens
llama_perf_context_print:    graphs reused =         39
Llama.generate: 203 prefix-match hit, remaining 59 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     241.66 ms /    59 tokens (    4.10 ms per token,   244.14 tokens per second)
llama_perf_context_print:        eval time =    1744.29 ms /    60 runs   (   29.07 ms per token,    34.40 tokens per second)
llama_perf_context_print:       total time =    4310.02 ms /   119 tokens
llama_perf_context_print:    graphs reused =         59
Llama.generate: 203 prefix-match hit, remaining 44 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     233.85 ms /    44 tokens (    5.31 ms per token,   188.15 tokens per second)
llama_perf_context_print:        eval time =    1964.33 ms /    68 runs   (   28.89 ms per token,    34.62 tokens per second)
llama_perf_context_print:       total time =    4848.17 ms /   112 tokens
llama_perf_context_print:    graphs reused =         66
Llama.generate: 204 prefix-match hit, remaining 39 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     232.01 ms /    39 tokens (    5.95 ms per token,   168.09 tokens per second)
llama_perf_context_print:        eval time =    1318.98 ms /    46 runs   (   28.67 ms per token,    34.88 tokens per second)
llama_perf_context_print:       total time =    3321.55 ms /    85 tokens
llama_perf_context_print:    graphs reused =         44
Llama.generate: 204 prefix-match hit, remaining 37 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     231.34 ms /    37 tokens (    6.25 ms per token,   159.94 tokens per second)
llama_perf_context_print:        eval time =    1897.37 ms /    66 runs   (   28.75 ms per token,    34.79 tokens per second)
llama_perf_context_print:       total time =    4694.52 ms /   103 tokens
llama_perf_context_print:    graphs reused =         64
Llama.generate: 220 prefix-match hit, remaining 21 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     226.25 ms /    21 tokens (   10.77 ms per token,    92.82 tokens per second)
llama_perf_context_print:        eval time =    1345.14 ms /    47 runs   (   28.62 ms per token,    34.94 tokens per second)
llama_perf_context_print:       total time =    3395.10 ms /    68 tokens
llama_perf_context_print:    graphs reused =         45
Llama.generate: 203 prefix-match hit, remaining 42 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     233.05 ms /    42 tokens (    5.55 ms per token,   180.22 tokens per second)
llama_perf_context_print:        eval time =    1583.64 ms /    55 runs   (   28.79 ms per token,    34.73 tokens per second)
llama_perf_context_print:       total time =    3973.00 ms /    97 tokens
llama_perf_context_print:    graphs reused =         53
Llama.generate: 203 prefix-match hit, remaining 42 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     233.05 ms /    42 tokens (    5.55 ms per token,   180.22 tokens per second)
llama_perf_context_print:        eval time =     654.18 ms /    23 runs   (   28.44 ms per token,    35.16 tokens per second)
llama_perf_context_print:       total time =    1764.35 ms /    65 tokens
llama_perf_context_print:    graphs reused =         21
Llama.generate: 244 prefix-match hit, remaining 1 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =       0.00 ms /     1 tokens (    0.00 ms per token,      inf tokens per second)
llama_perf_context_print:        eval time =     682.18 ms /    24 runs   (   28.42 ms per token,    35.18 tokens per second)
llama_perf_context_print:       total time =    1572.16 ms /    25 tokens
llama_perf_context_print:    graphs reused =         22
Llama.generate: 244 prefix-match hit, remaining 1 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =       0.00 ms /     1 tokens (    0.00 ms per token,      inf tokens per second)
llama_perf_context_print:        eval time =     682.32 ms /    24 runs   (   28.43 ms per token,    35.17 tokens per second)
llama_perf_context_print:       total time =    1577.54 ms /    25 tokens
llama_perf_context_print:    graphs reused =         22
Llama.generate: 244 prefix-match hit, remaining 1 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =       0.00 ms /     1 tokens (    0.00 ms per token,      inf tokens per second)
llama_perf_context_print:        eval time =     682.33 ms /    24 runs   (   28.43 ms per token,    35.17 tokens per second)
llama_perf_context_print:       total time =    1583.99 ms /    25 tokens
llama_perf_context_print:    graphs reused =         22
Llama.generate: 232 prefix-match hit, remaining 16 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     233.06 ms /    16 tokens (   14.57 ms per token,    68.65 tokens per second)
llama_perf_context_print:        eval time =    1414.83 ms /    49 runs   (   28.87 ms per token,    34.63 tokens per second)
llama_perf_context_print:       total time =    3573.79 ms /    65 tokens
llama_perf_context_print:    graphs reused =         47
Llama.generate: 232 prefix-match hit, remaining 13 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     230.41 ms /    13 tokens (   17.72 ms per token,    56.42 tokens per second)
llama_perf_context_print:        eval time =     655.27 ms /    23 runs   (   28.49 ms per token,    35.10 tokens per second)
llama_perf_context_print:       total time =    1790.80 ms /    36 tokens
llama_perf_context_print:    graphs reused =         21
Llama.generate: 244 prefix-match hit, remaining 1 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =       0.00 ms /     1 tokens (    0.00 ms per token,      inf tokens per second)
llama_perf_context_print:        eval time =     682.91 ms /    24 runs   (   28.45 ms per token,    35.14 tokens per second)
llama_perf_context_print:       total time =    1587.12 ms /    25 tokens
llama_perf_context_print:    graphs reused =         22
Llama.generate: 244 prefix-match hit, remaining 1 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =       0.00 ms /     1 tokens (    0.00 ms per token,      inf tokens per second)
llama_perf_context_print:        eval time =     681.98 ms /    24 runs   (   28.42 ms per token,    35.19 tokens per second)
llama_perf_context_print:       total time =    1573.44 ms /    25 tokens
llama_perf_context_print:    graphs reused =         22
Llama.generate: 232 prefix-match hit, remaining 16 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     232.99 ms /    16 tokens (   14.56 ms per token,    68.67 tokens per second)
llama_perf_context_print:        eval time =    1414.40 ms /    49 runs   (   28.87 ms per token,    34.64 tokens per second)
llama_perf_context_print:       total time =    3504.43 ms /    65 tokens
llama_perf_context_print:    graphs reused =         47
Llama.generate: 232 prefix-match hit, remaining 13 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     230.13 ms /    13 tokens (   17.70 ms per token,    56.49 tokens per second)
llama_perf_context_print:        eval time =     655.05 ms /    23 runs   (   28.48 ms per token,    35.11 tokens per second)
llama_perf_context_print:       total time =    1767.80 ms /    36 tokens
llama_perf_context_print:    graphs reused =         21
Llama.generate: 244 prefix-match hit, remaining 1 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =       0.00 ms /     1 tokens (    0.00 ms per token,      inf tokens per second)
llama_perf_context_print:        eval time =     682.46 ms /    24 runs   (   28.44 ms per token,    35.17 tokens per second)
llama_perf_context_print:       total time =    1562.33 ms /    25 tokens
llama_perf_context_print:    graphs reused =         22
Llama.generate: 232 prefix-match hit, remaining 16 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     232.94 ms /    16 tokens (   14.56 ms per token,    68.69 tokens per second)
llama_perf_context_print:        eval time =    1414.41 ms /    49 runs   (   28.87 ms per token,    34.64 tokens per second)
llama_perf_context_print:       total time =    3537.91 ms /    65 tokens
llama_perf_context_print:    graphs reused =         47
Llama.generate: 232 prefix-match hit, remaining 13 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     230.06 ms /    13 tokens (   17.70 ms per token,    56.51 tokens per second)
llama_perf_context_print:        eval time =     655.18 ms /    23 runs   (   28.49 ms per token,    35.10 tokens per second)
llama_perf_context_print:       total time =    1778.06 ms /    36 tokens
llama_perf_context_print:    graphs reused =         21
Llama.generate: 232 prefix-match hit, remaining 16 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     232.98 ms /    16 tokens (   14.56 ms per token,    68.68 tokens per second)
llama_perf_context_print:        eval time =    1414.70 ms /    49 runs   (   28.87 ms per token,    34.64 tokens per second)
llama_perf_context_print:       total time =    3536.96 ms /    65 tokens
llama_perf_context_print:    graphs reused =         47
Llama.generate: 247 prefix-match hit, remaining 1 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =       0.00 ms /     1 tokens (    0.00 ms per token,      inf tokens per second)
llama_perf_context_print:        eval time =    1442.75 ms /    50 runs   (   28.85 ms per token,    34.66 tokens per second)
llama_perf_context_print:       total time =    3333.89 ms /    51 tokens
llama_perf_context_print:    graphs reused =         48

Claims: 20
Candidate pairs: 23
Redundant copies: 7
Redundancy: 35.00%
Elapsed seconds: 66.9

Evaluating article 7/30
Event: 20 Article: 20.5

Llama.generate: 203 prefix-match hit, remaining 49 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     248.18 ms /    49 tokens (    5.06 ms per token,   197.44 tokens per second)
llama_perf_context_print:        eval time =    1332.40 ms /    46 runs   (   28.97 ms per token,    34.52 tokens per second)
llama_perf_context_print:       total time =    3269.94 ms /    95 tokens
llama_perf_context_print:    graphs reused =         44
Llama.generate: 228 prefix-match hit, remaining 40 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     234.55 ms /    40 tokens (    5.86 ms per token,   170.54 tokens per second)
llama_perf_context_print:        eval time =    2498.44 ms /    86 runs   (   29.05 ms per token,    34.42 tokens per second)
llama_perf_context_print:       total time =    5917.18 ms /   126 tokens
llama_perf_context_print:    graphs reused =         85
Llama.generate: 204 prefix-match hit, remaining 61 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     242.38 ms /    61 tokens (    3.97 ms per token,   251.67 tokens per second)
llama_perf_context_print:        eval time =    2295.28 ms /    79 runs   (   29.05 ms per token,    34.42 tokens per second)
llama_perf_context_print:       total time =    5474.56 ms /   140 tokens
llama_perf_context_print:    graphs reused =         78

Claims: 17
Candidate pairs: 3
Redundant copies: 0
Redundancy: 0.00%
Elapsed seconds: 17.3

Evaluating article 8/30
Event: 20 Article: 20.7

Llama.generate: 203 prefix-match hit, remaining 35 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     230.90 ms /    35 tokens (    6.60 ms per token,   151.58 tokens per second)
llama_perf_context_print:        eval time =    1427.96 ms /    50 runs   (   28.56 ms per token,    35.01 tokens per second)
llama_perf_context_print:       total time =    3577.13 ms /    85 tokens
llama_perf_context_print:    graphs reused =         48

Claims: 11
Candidate pairs: 1
Redundant copies: 0
Redundancy: 0.00%
Elapsed seconds: 4.6

Evaluating article 9/30
Event: 20 Article: 20.8
Claims: 22
Candidate pairs: 0
Redundant copies: 0
Redundancy: 0.00%
Elapsed seconds: 1.7

Evaluating article 10/30
Event: 20 Article: 20.1

Llama.generate: 203 prefix-match hit, remaining 41 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     232.71 ms /    41 tokens (    5.68 ms per token,   176.19 tokens per second)
llama_perf_context_print:        eval time =    1638.67 ms /    57 runs   (   28.75 ms per token,    34.78 tokens per second)
llama_perf_context_print:       total time =    3963.61 ms /    98 tokens
llama_perf_context_print:    graphs reused =         55

Claims: 9
Candidate pairs: 1
Redundant copies: 1
Redundancy: 11.11%
Elapsed seconds: 4.2

Evaluating article 11/30
Event: 41 Article: 41.9
Claims: 49
Candidate pairs: 0
Redundant copies: 0
Redundancy: 0.00%
Elapsed seconds: 3.3

Evaluating article 12/30
Event: 41 Article: 41.2

Llama.generate: 203 prefix-match hit, remaining 27 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     227.97 ms /    27 tokens (    8.44 ms per token,   118.44 tokens per second)
llama_perf_context_print:        eval time =    1647.09 ms /    58 runs   (   28.40 ms per token,    35.21 tokens per second)
llama_perf_context_print:       total time =    4022.33 ms /    85 tokens
llama_perf_context_print:    graphs reused =         56
Llama.generate: 203 prefix-match hit, remaining 61 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     242.43 ms /    61 tokens (    3.97 ms per token,   251.62 tokens per second)
llama_perf_context_print:        eval time =    1482.09 ms /    51 runs   (   29.06 ms per token,    34.41 tokens per second)
llama_perf_context_print:       total time =    3603.41 ms /   112 tokens
llama_perf_context_print:    graphs reused =         50

Claims: 60
Candidate pairs: 2
Redundant copies: 1
Redundancy: 1.67%
Elapsed seconds: 10.3

Evaluating article 13/30
Event: 41 Article: 41.3

Llama.generate: 203 prefix-match hit, remaining 22 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     226.42 ms /    22 tokens (   10.29 ms per token,    97.16 tokens per second)
llama_perf_context_print:        eval time =    1554.03 ms /    55 runs   (   28.26 ms per token,    35.39 tokens per second)
llama_perf_context_print:       total time =    3840.84 ms /    77 tokens
llama_perf_context_print:    graphs reused =         53
Llama.generate: 224 prefix-match hit, remaining 1 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =       0.00 ms /     1 tokens (    0.00 ms per token,      inf tokens per second)
llama_perf_context_print:        eval time =    1582.53 ms /    56 runs   (   28.26 ms per token,    35.39 tokens per second)
llama_perf_context_print:       total time =    3723.26 ms /    57 tokens
llama_perf_context_print:    graphs reused =         54
Llama.generate: 203 prefix-match hit, remaining 52 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     236.12 ms /    52 tokens (    4.54 ms per token,   220.22 tokens per second)
llama_perf_context_print:        eval time =    1511.70 ms /    52 runs   (   29.07 ms per token,    34.40 tokens per second)
llama_perf_context_print:       total time =    3747.08 ms /   104 tokens
llama_perf_context_print:    graphs reused =         50
Llama.generate: 203 prefix-match hit, remaining 26 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     227.79 ms /    26 tokens (    8.76 ms per token,   114.14 tokens per second)
llama_perf_context_print:        eval time =     635.54 ms /    23 runs   (   27.63 ms per token,    36.19 tokens per second)
llama_perf_context_print:       total time =    1718.85 ms /    49 tokens
llama_perf_context_print:    graphs reused =         22
Llama.generate: 203 prefix-match hit, remaining 48 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     234.93 ms /    48 tokens (    4.89 ms per token,   204.32 tokens per second)
llama_perf_context_print:        eval time =    1476.81 ms /    51 runs   (   28.96 ms per token,    34.53 tokens per second)
llama_perf_context_print:       total time =    3672.04 ms /    99 tokens
llama_perf_context_print:    graphs reused =         49
Llama.generate: 203 prefix-match hit, remaining 46 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     234.46 ms /    46 tokens (    5.10 ms per token,   196.19 tokens per second)
llama_perf_context_print:        eval time =    1386.93 ms /    48 runs   (   28.89 ms per token,    34.61 tokens per second)
llama_perf_context_print:       total time =    3473.19 ms /    94 tokens
llama_perf_context_print:    graphs reused =         46

Claims: 64
Candidate pairs: 6
Redundant copies: 2
Redundancy: 3.12%
Elapsed seconds: 22.4

Evaluating article 14/30
Event: 41 Article: 41.5

Llama.generate: 203 prefix-match hit, remaining 33 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     229.89 ms /    33 tokens (    6.97 ms per token,   143.55 tokens per second)
llama_perf_context_print:        eval time =    1425.99 ms /    50 runs   (   28.52 ms per token,    35.06 tokens per second)
llama_perf_context_print:       total time =    3583.70 ms /    83 tokens
llama_perf_context_print:    graphs reused =         48

Claims: 39
Candidate pairs: 1
Redundant copies: 0
Redundancy: 0.00%
Elapsed seconds: 5.1

Evaluating article 15/30
Event: 41 Article: 41.6

Llama.generate: 203 prefix-match hit, remaining 37 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     231.46 ms /    37 tokens (    6.26 ms per token,   159.85 tokens per second)
llama_perf_context_print:        eval time =    1430.52 ms /    50 runs   (   28.61 ms per token,    34.95 tokens per second)
llama_perf_context_print:       total time =    3593.14 ms /    87 tokens
llama_perf_context_print:    graphs reused =         48

Claims: 44
Candidate pairs: 1
Redundant copies: 0
Redundancy: 0.00%
Elapsed seconds: 5.1

Evaluating article 16/30
Event: 27 Article: 27.2

Llama.generate: 203 prefix-match hit, remaining 44 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     233.78 ms /    44 tokens (    5.31 ms per token,   188.21 tokens per second)
llama_perf_context_print:        eval time =    1064.05 ms /    37 runs   (   28.76 ms per token,    34.77 tokens per second)
llama_perf_context_print:       total time =    2706.13 ms /    81 tokens
llama_perf_context_print:    graphs reused =         35
Llama.generate: 203 prefix-match hit, remaining 32 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     229.58 ms /    32 tokens (    7.17 ms per token,   139.38 tokens per second)
llama_perf_context_print:        eval time =    1627.39 ms /    57 runs   (   28.55 ms per token,    35.03 tokens per second)
llama_perf_context_print:       total time =    4055.67 ms /    89 tokens
llama_perf_context_print:    graphs reused =         55

Claims: 42
Candidate pairs: 2
Redundant copies: 1
Redundancy: 2.38%
Elapsed seconds: 8.1

Evaluating article 17/30
Event: 27 Article: 27.3

Llama.generate: 203 prefix-match hit, remaining 42 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     233.21 ms /    42 tokens (    5.55 ms per token,   180.09 tokens per second)
llama_perf_context_print:        eval time =     654.12 ms /    23 runs   (   28.44 ms per token,    35.16 tokens per second)
llama_perf_context_print:       total time =    1752.17 ms /    65 tokens
llama_perf_context_print:    graphs reused =         21

Claims: 37
Candidate pairs: 1
Redundant copies: 1
Redundancy: 2.70%
Elapsed seconds: 2.8

Evaluating article 18/30
Event: 27 Article: 27.4

Llama.generate: 203 prefix-match hit, remaining 48 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     234.99 ms /    48 tokens (    4.90 ms per token,   204.26 tokens per second)
llama_perf_context_print:        eval time =    1678.77 ms /    58 runs   (   28.94 ms per token,    34.55 tokens per second)
llama_perf_context_print:       total time =    4156.57 ms /   106 tokens
llama_perf_context_print:    graphs reused =         56

Claims: 37
Candidate pairs: 1
Redundant copies: 1
Redundancy: 2.70%
Elapsed seconds: 5.6

Evaluating article 19/30
Event: 27 Article: 27.5
Claims: 32
Candidate pairs: 0
Redundant copies: 0
Redundancy: 0.00%
Elapsed seconds: 1.0

Evaluating article 20/30
Event: 27 Article: 27.6

Llama.generate: 203 prefix-match hit, remaining 58 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     241.10 ms /    58 tokens (    4.16 ms per token,   240.56 tokens per second)
llama_perf_context_print:        eval time =    1743.12 ms /    60 runs   (   29.05 ms per token,    34.42 tokens per second)
llama_perf_context_print:       total time =    4310.45 ms /   118 tokens
llama_perf_context_print:    graphs reused =         59
Llama.generate: 203 prefix-match hit, remaining 34 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     230.23 ms /    34 tokens (    6.77 ms per token,   147.68 tokens per second)
llama_perf_context_print:        eval time =    1718.19 ms /    60 runs   (   28.64 ms per token,    34.92 tokens per second)
llama_perf_context_print:       total time =    4280.35 ms /    94 tokens
llama_perf_context_print:    graphs reused =         58
Llama.generate: 203 prefix-match hit, remaining 37 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     231.34 ms /    37 tokens (    6.25 ms per token,   159.94 tokens per second)
llama_perf_context_print:        eval time =    1954.99 ms /    68 runs   (   28.75 ms per token,    34.78 tokens per second)
llama_perf_context_print:       total time =    4836.33 ms /   105 tokens
llama_perf_context_print:    graphs reused =         66
Llama.generate: 203 prefix-match hit, remaining 42 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     233.04 ms /    42 tokens (    5.55 ms per token,   180.23 tokens per second)
llama_perf_context_print:        eval time =    1294.29 ms /    45 runs   (   28.76 ms per token,    34.77 tokens per second)
llama_perf_context_print:       total time =    3259.06 ms /    87 tokens
llama_perf_context_print:    graphs reused =         43

Claims: 46
Candidate pairs: 4
Redundant copies: 0
Redundancy: 0.00%
Elapsed seconds: 18.0

Evaluating article 21/30
Event: 34 Article: 34.2

Llama.generate: 203 prefix-match hit, remaining 88 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     313.86 ms /    88 tokens (    3.57 ms per token,   280.38 tokens per second)
llama_perf_context_print:        eval time =    1162.45 ms /    40 runs   (   29.06 ms per token,    34.41 tokens per second)
llama_perf_context_print:       total time =    3005.78 ms /   128 tokens
llama_perf_context_print:    graphs reused =         39
Llama.generate: 249 prefix-match hit, remaining 26 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     229.59 ms /    26 tokens (    8.83 ms per token,   113.25 tokens per second)
llama_perf_context_print:        eval time =    1917.90 ms /    66 runs   (   29.06 ms per token,    34.41 tokens per second)
llama_perf_context_print:       total time =    4700.24 ms /    92 tokens
llama_perf_context_print:    graphs reused =         65
Llama.generate: 203 prefix-match hit, remaining 39 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     232.28 ms /    39 tokens (    5.96 ms per token,   167.90 tokens per second)
llama_perf_context_print:        eval time =    2130.54 ms /    74 runs   (   28.79 ms per token,    34.73 tokens per second)
llama_perf_context_print:       total time =    5256.00 ms /   113 tokens
llama_perf_context_print:    graphs reused =         72

Claims: 29
Candidate pairs: 3
Redundant copies: 1
Redundancy: 3.45%
Elapsed seconds: 14.3

Evaluating article 22/30
Event: 34 Article: 34.3

Llama.generate: 203 prefix-match hit, remaining 54 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     239.40 ms /    54 tokens (    4.43 ms per token,   225.56 tokens per second)
llama_perf_context_print:        eval time =    1772.34 ms /    61 runs   (   29.05 ms per token,    34.42 tokens per second)
llama_perf_context_print:       total time =    4376.82 ms /   115 tokens
llama_perf_context_print:    graphs reused =         60
Llama.generate: 203 prefix-match hit, remaining 38 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     231.70 ms /    38 tokens (    6.10 ms per token,   164.01 tokens per second)
llama_perf_context_print:        eval time =    2042.17 ms /    71 runs   (   28.76 ms per token,    34.77 tokens per second)
llama_perf_context_print:       total time =    5043.57 ms /   109 tokens
llama_perf_context_print:    graphs reused =         69
Llama.generate: 203 prefix-match hit, remaining 32 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     229.78 ms /    32 tokens (    7.18 ms per token,   139.26 tokens per second)
llama_perf_context_print:        eval time =    1424.38 ms /    50 runs   (   28.49 ms per token,    35.10 tokens per second)
llama_perf_context_print:       total time =    3586.59 ms /    82 tokens
llama_perf_context_print:    graphs reused =         48

Claims: 24
Candidate pairs: 3
Redundant copies: 0
Redundancy: 0.00%
Elapsed seconds: 13.8

Evaluating article 23/30
Event: 34 Article: 34.4

Llama.generate: 203 prefix-match hit, remaining 40 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     232.30 ms /    40 tokens (    5.81 ms per token,   172.19 tokens per second)
llama_perf_context_print:        eval time =    1754.19 ms /    61 runs   (   28.76 ms per token,    34.77 tokens per second)
llama_perf_context_print:       total time =    4357.62 ms /   101 tokens
llama_perf_context_print:    graphs reused =         59
Llama.generate: 203 prefix-match hit, remaining 42 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     232.96 ms /    42 tokens (    5.55 ms per token,   180.29 tokens per second)
llama_perf_context_print:        eval time =    1582.72 ms /    55 runs   (   28.78 ms per token,    34.75 tokens per second)
llama_perf_context_print:       total time =    3956.69 ms /    97 tokens
llama_perf_context_print:    graphs reused =         53

Claims: 37
Candidate pairs: 2
Redundant copies: 0
Redundancy: 0.00%
Elapsed seconds: 9.7

Evaluating article 24/30
Event: 34 Article: 34.8

Llama.generate: 203 prefix-match hit, remaining 48 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     234.90 ms /    48 tokens (    4.89 ms per token,   204.34 tokens per second)
llama_perf_context_print:        eval time =    1301.53 ms /    45 runs   (   28.92 ms per token,    34.57 tokens per second)
llama_perf_context_print:       total time =    3269.01 ms /    93 tokens
llama_perf_context_print:    graphs reused =         43

Claims: 44
Candidate pairs: 1
Redundant copies: 0
Redundancy: 0.00%
Elapsed seconds: 4.8

Evaluating article 25/30
Event: 34 Article: 34.9

Llama.generate: 203 prefix-match hit, remaining 34 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     230.13 ms /    34 tokens (    6.77 ms per token,   147.75 tokens per second)
llama_perf_context_print:        eval time =    1338.90 ms /    47 runs   (   28.49 ms per token,    35.10 tokens per second)
llama_perf_context_print:       total time =    3380.70 ms /    81 tokens
llama_perf_context_print:    graphs reused =         45

Claims: 42
Candidate pairs: 1
Redundant copies: 1
Redundancy: 2.38%
Elapsed seconds: 4.3

Evaluating article 26/30
Event: 13 Article: 13.1

Llama.generate: 203 prefix-match hit, remaining 29 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     228.58 ms /    29 tokens (    7.88 ms per token,   126.87 tokens per second)
llama_perf_context_print:        eval time =    1447.83 ms /    51 runs   (   28.39 ms per token,    35.23 tokens per second)
llama_perf_context_print:       total time =    3649.65 ms /    80 tokens
llama_perf_context_print:    graphs reused =         49
Llama.generate: 203 prefix-match hit, remaining 53 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     236.46 ms /    53 tokens (    4.46 ms per token,   224.14 tokens per second)
llama_perf_context_print:        eval time =    2295.47 ms /    79 runs   (   29.06 ms per token,    34.42 tokens per second)
llama_perf_context_print:       total time =    5612.28 ms /   132 tokens
llama_perf_context_print:    graphs reused =         78
Llama.generate: 223 prefix-match hit, remaining 23 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     226.96 ms /    23 tokens (    9.87 ms per token,   101.34 tokens per second)
llama_perf_context_print:        eval time =    2949.13 ms /   102 runs   (   28.91 ms per token,    34.59 tokens per second)
llama_perf_context_print:       total time =    7214.45 ms /   125 tokens
llama_perf_context_print:    graphs reused =        100
Llama.generate: 204 prefix-match hit, remaining 36 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     231.06 ms /    36 tokens (    6.42 ms per token,   155.80 tokens per second)
llama_perf_context_print:        eval time =    2040.73 ms /    71 runs   (   28.74 ms per token,    34.79 tokens per second)
llama_perf_context_print:       total time =    5055.18 ms /   107 tokens
llama_perf_context_print:    graphs reused =         69
Llama.generate: 203 prefix-match hit, remaining 47 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     234.75 ms /    47 tokens (    4.99 ms per token,   200.21 tokens per second)
llama_perf_context_print:        eval time =    1765.69 ms /    61 runs   (   28.95 ms per token,    34.55 tokens per second)
llama_perf_context_print:       total time =    4386.13 ms /   108 tokens
llama_perf_context_print:    graphs reused =         59
Llama.generate: 203 prefix-match hit, remaining 41 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     232.75 ms /    41 tokens (    5.68 ms per token,   176.15 tokens per second)
llama_perf_context_print:        eval time =    1872.69 ms /    65 runs   (   28.81 ms per token,    34.71 tokens per second)
llama_perf_context_print:       total time =    4648.64 ms /   106 tokens
llama_perf_context_print:    graphs reused =         63

Claims: 32
Candidate pairs: 6
Redundant copies: 0
Redundancy: 0.00%
Elapsed seconds: 32.0

Evaluating article 27/30
Event: 13 Article: 13.3

Llama.generate: 203 prefix-match hit, remaining 34 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     230.06 ms /    34 tokens (    6.77 ms per token,   147.79 tokens per second)
llama_perf_context_print:        eval time =    1774.21 ms /    62 runs   (   28.62 ms per token,    34.95 tokens per second)
llama_perf_context_print:       total time =    4325.12 ms /    96 tokens
llama_perf_context_print:    graphs reused =         60
Llama.generate: 203 prefix-match hit, remaining 29 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     228.63 ms /    29 tokens (    7.88 ms per token,   126.84 tokens per second)
llama_perf_context_print:        eval time =    1098.97 ms /    39 runs   (   28.18 ms per token,    35.49 tokens per second)
llama_perf_context_print:       total time =    2764.26 ms /    68 tokens
llama_perf_context_print:    graphs reused =         37
Llama.generate: 203 prefix-match hit, remaining 39 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     231.96 ms /    39 tokens (    5.95 ms per token,   168.14 tokens per second)
llama_perf_context_print:        eval time =    2274.75 ms /    79 runs   (   28.79 ms per token,    34.73 tokens per second)
llama_perf_context_print:       total time =    5455.76 ms /   118 tokens
llama_perf_context_print:    graphs reused =         77
Llama.generate: 203 prefix-match hit, remaining 47 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     234.54 ms /    47 tokens (    4.99 ms per token,   200.39 tokens per second)
llama_perf_context_print:        eval time =    2054.20 ms /    71 runs   (   28.93 ms per token,    34.56 tokens per second)
llama_perf_context_print:       total time =    4968.52 ms /   118 tokens
llama_perf_context_print:    graphs reused =         69
Llama.generate: 203 prefix-match hit, remaining 39 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     232.08 ms /    39 tokens (    5.95 ms per token,   168.04 tokens per second)
llama_perf_context_print:        eval time =    1433.84 ms /    50 runs   (   28.68 ms per token,    34.87 tokens per second)
llama_perf_context_print:       total time =    3520.22 ms /    89 tokens
llama_perf_context_print:    graphs reused =         48

Claims: 34
Candidate pairs: 5
Redundant copies: 0
Redundancy: 0.00%
Elapsed seconds: 22.5

Evaluating article 28/30
Event: 13 Article: 13.4

Llama.generate: 203 prefix-match hit, remaining 40 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     232.26 ms /    40 tokens (    5.81 ms per token,   172.22 tokens per second)
llama_perf_context_print:        eval time =    1841.11 ms /    64 runs   (   28.77 ms per token,    34.76 tokens per second)
llama_perf_context_print:       total time =    4475.92 ms /   104 tokens
llama_perf_context_print:    graphs reused =         62
Llama.generate: 203 prefix-match hit, remaining 45 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     234.03 ms /    45 tokens (    5.20 ms per token,   192.29 tokens per second)
llama_perf_context_print:        eval time =    1500.47 ms /    52 runs   (   28.86 ms per token,    34.66 tokens per second)
llama_perf_context_print:       total time =    3675.03 ms /    97 tokens
llama_perf_context_print:    graphs reused =         50
Llama.generate: 220 prefix-match hit, remaining 15 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     232.58 ms /    15 tokens (   15.51 ms per token,    64.49 tokens per second)
llama_perf_context_print:        eval time =    1713.48 ms /    60 runs   (   28.56 ms per token,    35.02 tokens per second)
llama_perf_context_print:       total time =    4188.79 ms /    75 tokens
llama_perf_context_print:    graphs reused =         58
Llama.generate: 207 prefix-match hit, remaining 37 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     231.24 ms /    37 tokens (    6.25 ms per token,   160.01 tokens per second)
llama_perf_context_print:        eval time =    1465.90 ms /    51 runs   (   28.74 ms per token,    34.79 tokens per second)
llama_perf_context_print:       total time =    3608.92 ms /    88 tokens
llama_perf_context_print:    graphs reused =         49
Llama.generate: 203 prefix-match hit, remaining 34 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     230.24 ms /    34 tokens (    6.77 ms per token,   147.67 tokens per second)
llama_perf_context_print:        eval time =    1281.72 ms /    45 runs   (   28.48 ms per token,    35.11 tokens per second)
llama_perf_context_print:       total time =    3184.31 ms /    79 tokens
llama_perf_context_print:    graphs reused =         43
Llama.generate: 203 prefix-match hit, remaining 36 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     231.11 ms /    36 tokens (    6.42 ms per token,   155.77 tokens per second)
llama_perf_context_print:        eval time =    1633.15 ms /    57 runs   (   28.65 ms per token,    34.90 tokens per second)
llama_perf_context_print:       total time =    3996.60 ms /    93 tokens
llama_perf_context_print:    graphs reused =         55
Llama.generate: 223 prefix-match hit, remaining 17 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     224.96 ms /    17 tokens (   13.23 ms per token,    75.57 tokens per second)
llama_perf_context_print:        eval time =    1228.03 ms /    43 runs   (   28.56 ms per token,    35.02 tokens per second)
llama_perf_context_print:       total time =    3063.96 ms /    60 tokens
llama_perf_context_print:    graphs reused =         41
Llama.generate: 203 prefix-match hit, remaining 50 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     235.37 ms /    50 tokens (    4.71 ms per token,   212.43 tokens per second)
llama_perf_context_print:        eval time =    1625.11 ms /    56 runs   (   29.02 ms per token,    34.46 tokens per second)
llama_perf_context_print:       total time =    3967.47 ms /   106 tokens
llama_perf_context_print:    graphs reused =         54
Llama.generate: 203 prefix-match hit, remaining 61 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     242.39 ms /    61 tokens (    3.97 ms per token,   251.66 tokens per second)
llama_perf_context_print:        eval time =    1918.63 ms /    66 runs   (   29.07 ms per token,    34.40 tokens per second)
llama_perf_context_print:       total time =    4656.13 ms /   127 tokens
llama_perf_context_print:    graphs reused =         65
Llama.generate: 203 prefix-match hit, remaining 32 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     229.79 ms /    32 tokens (    7.18 ms per token,   139.26 tokens per second)
llama_perf_context_print:        eval time =    1337.35 ms /    47 runs   (   28.45 ms per token,    35.14 tokens per second)
llama_perf_context_print:       total time =    3343.63 ms /    79 tokens
llama_perf_context_print:    graphs reused =         45
Llama.generate: 203 prefix-match hit, remaining 33 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     229.83 ms /    33 tokens (    6.96 ms per token,   143.59 tokens per second)
llama_perf_context_print:        eval time =    1367.54 ms /    48 runs   (   28.49 ms per token,    35.10 tokens per second)
llama_perf_context_print:       total time =    3429.49 ms /    81 tokens
llama_perf_context_print:    graphs reused =         46
Llama.generate: 203 prefix-match hit, remaining 79 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     311.95 ms /    79 tokens (    3.95 ms per token,   253.24 tokens per second)
llama_perf_context_print:        eval time =    1889.49 ms /    65 runs   (   29.07 ms per token,    34.40 tokens per second)
llama_perf_context_print:       total time =    4667.95 ms /   144 tokens
llama_perf_context_print:    graphs reused =         64
Llama.generate: 203 prefix-match hit, remaining 54 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     239.40 ms /    54 tokens (    4.43 ms per token,   225.56 tokens per second)
llama_perf_context_print:        eval time =    2238.26 ms /    77 runs   (   29.07 ms per token,    34.40 tokens per second)
llama_perf_context_print:       total time =    5414.12 ms /   131 tokens
llama_perf_context_print:    graphs reused =         76

Claims: 71
Candidate pairs: 13
Redundant copies: 1
Redundancy: 1.41%
Elapsed seconds: 53.3

Evaluating article 29/30
Event: 13 Article: 13.6

Llama.generate: 203 prefix-match hit, remaining 32 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     230.08 ms /    32 tokens (    7.19 ms per token,   139.08 tokens per second)
llama_perf_context_print:        eval time =    1799.95 ms /    63 runs   (   28.57 ms per token,    35.00 tokens per second)
llama_perf_context_print:       total time =    4379.87 ms /    95 tokens
llama_perf_context_print:    graphs reused =         61
Llama.generate: 203 prefix-match hit, remaining 33 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     229.95 ms /    33 tokens (    6.97 ms per token,   143.51 tokens per second)
llama_perf_context_print:        eval time =    1627.21 ms /    57 runs   (   28.55 ms per token,    35.03 tokens per second)
llama_perf_context_print:       total time =    3978.38 ms /    90 tokens
llama_perf_context_print:    graphs reused =         55
Llama.generate: 203 prefix-match hit, remaining 33 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     229.85 ms /    33 tokens (    6.97 ms per token,   143.57 tokens per second)
llama_perf_context_print:        eval time =    1569.35 ms /    55 runs   (   28.53 ms per token,    35.05 tokens per second)
llama_perf_context_print:       total time =    3841.45 ms /    88 tokens
llama_perf_context_print:    graphs reused =         53
Llama.generate: 216 prefix-match hit, remaining 21 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     226.17 ms /    21 tokens (   10.77 ms per token,    92.85 tokens per second)
llama_perf_context_print:        eval time =    1890.10 ms /    66 runs   (   28.64 ms per token,    34.92 tokens per second)
llama_perf_context_print:       total time =    4574.94 ms /    87 tokens
llama_perf_context_print:    graphs reused =         64
Llama.generate: 203 prefix-match hit, remaining 40 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     232.28 ms /    40 tokens (    5.81 ms per token,   172.20 tokens per second)
llama_perf_context_print:        eval time =    1551.55 ms /    54 runs   (   28.73 ms per token,    34.80 tokens per second)
llama_perf_context_print:       total time =    3787.32 ms /    94 tokens
llama_perf_context_print:    graphs reused =         52

Claims: 33
Candidate pairs: 5
Redundant copies: 0
Redundancy: 0.00%
Elapsed seconds: 21.6

Evaluating article 30/30
Event: 13 Article: 13.5

Llama.generate: 203 prefix-match hit, remaining 33 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =     229.79 ms /    33 tokens (    6.96 ms per token,   143.61 tokens per second)
llama_perf_context_print:        eval time =    1395.64 ms /    49 runs   (   28.48 ms per token,    35.11 tokens per second)
llama_perf_context_print:       total time =    3447.58 ms /    82 tokens
llama_perf_context_print:    graphs reused =         47
Llama.generate: 227 prefix-match hit, remaining 8 prompt tokens to eval
llama_perf_context_print:        load time =    1551.77 ms
llama_perf_context_print: prompt eval time =      73.56 ms /     8 tokens (    9.20 ms per token,   108.75 tokens per second)
llama_perf_context_print:        eval time =    1598.19 ms /    56 runs   (   28.54 ms per token,    35.04 tokens per second)
llama_perf_context_print:       total time =    3758.00 ms /    64 tokens
llama_perf_context_print:    graphs reused =         54

Claims: 26
Candidate pairs: 2
Redundant copies: 1
Redundancy: 3.85%
Elapsed seconds: 7.7

Evaluation loop finished!
status
OK    30
Name: count, dtype: int64

In [29]:
import pandas as pd
from pathlib import Path

RESULTS_DIR = Path(
    "/project2/xiangren_1987/group_22/redundancy_results"
)

ARTICLE_FILE = RESULTS_DIR / "redundancy_by_article.csv"
SUMMARY_FILE = RESULTS_DIR / "redundancy_summary.csv"

# Load saved results
article_results_df = pd.read_csv(ARTICLE_FILE)

# Keep only successfully evaluated articles
successful = article_results_df[
    article_results_df["status"] == "OK"
].copy()

print("Successful articles:", len(successful))
print("Failed articles:", len(article_results_df) - len(successful))

Successful articles: 30
Failed articles: 0

In [30]:
total_articles = 30
THRESHOLD = 0.70

total_claims = int(successful["total_claims"].sum())
total_redundant = int(successful["redundant_copies"].sum())

overall_redundancy = (
    total_redundant / total_claims
    if total_claims > 0 else float("nan")
)

mean_article_redundancy = successful["redundancy_rate"].mean()

print("FENICE REDUNDANCY RESULTS")
print("-" * 40)
print("Articles evaluated:", len(successful))
print("Total claims:", total_claims)
print("Redundant copies:", total_redundant)
print(f"Overall redundancy rate: {overall_redundancy:.2%}")
print(f"Mean article redundancy: {mean_article_redundancy:.2%}")

FENICE REDUNDANCY RESULTS
----------------------------------------
Articles evaluated: 30
Total claims: 1014
Redundant copies: 23
Overall redundancy rate: 2.27%
Mean article redundancy: 3.13%

In [31]:
summary_df = pd.DataFrame([{
    "extractor": "FENICE T5-base",
    "redundancy_evaluator": "SBERT + Qwen3-8B",
    "sbert_model": "all-mpnet-base-v2",
    "sbert_threshold": THRESHOLD,
    "articles_evaluated": len(successful),
    "total_articles": total_articles,
    "claims_evaluated": total_claims,
    "redundant_copies": total_redundant,
    "overall_redundancy_rate": overall_redundancy,
    "mean_article_redundancy": mean_article_redundancy
}])

summary_df.to_csv(SUMMARY_FILE, index=False)

display(summary_df)

print("Summary saved successfully!")

,extractor,redundancy_evaluator,sbert_model,sbert_threshold,articles_evaluated,total_articles,claims_evaluated,redundant_copies,overall_redundancy_rate,mean_article_redundancy
0,FENICE T5-base,SBERT + Qwen3-8B,all-mpnet-base-v2,0.7,30,30,1014,23,0.022682,0.031312

Summary saved successfully!